/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID asiclab.kongu.edu)
#  Generated on:      Mon Jun  9 14:20:34 2025
#  Design:            simple_riscv
#  Command:           saveNetlist simple_riscv.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun  9 2025 12:45:00 IST (Jun  9 2025 07:15:00 UTC)
// Verification Directory fv/simple_riscv 
module simple_riscv (
	clk, 
	reset, 
	instruction, 
	data_in, 
	data_out, 
	addr, 
	mem_read, 
	mem_write);
   input clk;
   input reset;
   input [15:0] instruction;
   input [7:0] data_in;
   output [7:0] data_out;
   output [3:0] addr;
   output mem_read;
   output mem_write;

   // Internal wires
   wire FE_PHN6_n_62;
   wire FE_PHN5_instruction_12;
   wire FE_OFN588_n_584;
   wire [7:0] \reg_file[4] ;
   wire [7:0] \reg_file[1] ;
   wire [7:0] \reg_file[2] ;
   wire [7:0] \reg_file[3] ;
   wire [7:0] \reg_file[0] ;
   wire [7:0] \reg_file[5] ;
   wire [7:0] \reg_file[6] ;
   wire [7:0] \reg_file[7] ;
   wire [7:0] \reg_file[12] ;
   wire [7:0] \reg_file[9] ;
   wire [7:0] \reg_file[10] ;
   wire [7:0] \reg_file[11] ;
   wire [7:0] \reg_file[8] ;
   wire [7:0] \reg_file[13] ;
   wire [7:0] \reg_file[14] ;
   wire [7:0] \reg_file[15] ;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_269;
   wire n_270;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_274;
   wire n_276;
   wire n_277;
   wire n_278;
   wire n_279;
   wire n_280;
   wire n_281;
   wire n_282;
   wire n_283;
   wire n_284;
   wire n_285;
   wire n_286;
   wire n_288;
   wire n_289;
   wire n_290;
   wire n_291;
   wire n_292;
   wire n_293;
   wire n_294;
   wire n_295;
   wire n_296;
   wire n_297;
   wire n_298;
   wire n_299;
   wire n_300;
   wire n_301;
   wire n_302;
   wire n_303;
   wire n_304;
   wire n_305;
   wire n_306;
   wire n_307;
   wire n_308;
   wire n_310;
   wire n_311;
   wire n_312;
   wire n_313;
   wire n_314;
   wire n_315;
   wire n_316;
   wire n_317;
   wire n_318;
   wire n_320;
   wire n_321;
   wire n_322;
   wire n_323;
   wire n_324;
   wire n_325;
   wire n_326;
   wire n_327;
   wire n_328;
   wire n_329;
   wire n_330;
   wire n_331;
   wire n_332;
   wire n_333;
   wire n_334;
   wire n_335;
   wire n_336;
   wire n_337;
   wire n_338;
   wire n_339;
   wire n_340;
   wire n_341;
   wire n_342;
   wire n_343;
   wire n_344;
   wire n_345;
   wire n_346;
   wire n_347;
   wire n_348;
   wire n_349;
   wire n_350;
   wire n_351;
   wire n_352;
   wire n_353;
   wire n_354;
   wire n_355;
   wire n_356;
   wire n_357;
   wire n_358;
   wire n_359;
   wire n_360;
   wire n_362;
   wire n_363;
   wire n_364;
   wire n_365;
   wire n_366;
   wire n_367;
   wire n_368;
   wire n_369;
   wire n_370;
   wire n_371;
   wire n_372;
   wire n_373;
   wire n_374;
   wire n_375;
   wire n_376;
   wire n_377;
   wire n_378;
   wire n_379;
   wire n_380;
   wire n_381;
   wire n_382;
   wire n_383;
   wire n_384;
   wire n_385;
   wire n_386;
   wire n_387;
   wire n_388;
   wire n_389;
   wire n_390;
   wire n_391;
   wire n_392;
   wire n_393;
   wire n_394;
   wire n_395;
   wire n_396;
   wire n_397;
   wire n_398;
   wire n_399;
   wire n_400;
   wire n_401;
   wire n_402;
   wire n_403;
   wire n_404;
   wire n_405;
   wire n_406;
   wire n_407;
   wire n_408;
   wire n_409;
   wire n_410;
   wire n_411;
   wire n_412;
   wire n_413;
   wire n_414;
   wire n_415;
   wire n_416;
   wire n_417;
   wire n_418;
   wire n_419;
   wire n_420;
   wire n_421;
   wire n_422;
   wire n_423;
   wire n_424;
   wire n_425;
   wire n_426;
   wire n_427;
   wire n_428;
   wire n_429;
   wire n_430;
   wire n_432;
   wire n_434;
   wire n_435;
   wire n_436;
   wire n_437;
   wire n_438;
   wire n_439;
   wire n_440;
   wire n_441;
   wire n_443;
   wire n_444;
   wire n_445;
   wire n_446;
   wire n_447;
   wire n_448;
   wire n_449;
   wire n_450;
   wire n_451;
   wire n_452;
   wire n_453;
   wire n_454;
   wire n_455;
   wire n_456;
   wire n_457;
   wire n_458;
   wire n_460;
   wire n_461;
   wire n_462;
   wire n_463;
   wire n_464;
   wire n_465;
   wire n_466;
   wire n_467;
   wire n_468;
   wire n_469;
   wire n_470;
   wire n_471;
   wire n_472;
   wire n_473;
   wire n_475;
   wire n_476;
   wire n_477;
   wire n_479;
   wire n_480;
   wire n_481;
   wire n_482;
   wire n_484;
   wire n_485;
   wire n_486;
   wire n_488;
   wire n_489;
   wire n_490;
   wire n_491;
   wire n_492;
   wire n_493;
   wire n_494;
   wire n_495;
   wire n_496;
   wire n_497;
   wire n_498;
   wire n_499;
   wire n_500;
   wire n_501;
   wire n_502;
   wire n_503;
   wire n_504;
   wire n_506;
   wire n_507;
   wire n_508;
   wire n_509;
   wire n_510;
   wire n_511;
   wire n_512;
   wire n_513;
   wire n_514;
   wire n_515;
   wire n_516;
   wire n_517;
   wire n_518;
   wire n_519;
   wire n_520;
   wire n_521;
   wire n_522;
   wire n_523;
   wire n_525;
   wire n_526;
   wire n_527;
   wire n_528;
   wire n_529;
   wire n_530;
   wire n_531;
   wire n_532;
   wire n_533;
   wire n_534;
   wire n_537;
   wire n_538;
   wire n_540;
   wire n_541;
   wire n_542;
   wire n_543;
   wire n_544;
   wire n_547;
   wire n_548;
   wire n_549;
   wire n_550;
   wire n_551;
   wire n_552;
   wire n_553;
   wire n_554;
   wire n_555;
   wire n_556;
   wire n_557;
   wire n_559;
   wire n_560;
   wire n_561;
   wire n_562;
   wire n_563;
   wire n_564;
   wire n_565;
   wire n_566;
   wire n_567;
   wire n_568;
   wire n_569;
   wire n_570;
   wire n_571;
   wire n_572;
   wire n_573;
   wire n_574;
   wire n_575;
   wire n_576;
   wire n_577;
   wire n_578;
   wire n_579;
   wire n_580;
   wire n_581;
   wire n_582;
   wire n_583;
   wire n_584;
   wire n_596;
   wire n_597;
   wire n_598;
   wire n_599;
   wire n_600;
   wire n_601;
   wire n_602;
   wire n_603;
   wire n_604;
   wire n_605;
   wire n_606;
   wire n_607;

   CLKBUFX2 FE_PHC6_n_62 (.A(n_62),
	.Y(FE_PHN6_n_62));
   CLKBUFX2 FE_PHC5_instruction_12 (.A(instruction[12]),
	.Y(FE_PHN5_instruction_12));
   BUFX2 FE_OFC4_n_584 (.A(n_584),
	.Y(FE_OFN588_n_584));
   SDFFRHQX1 \reg_file_reg[4][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[4] [5]),
	.RN(FE_OFN588_n_584),
	.SE(n_575),
	.SI(\reg_file[4] [5]));
   SDFFRHQX1 \reg_file_reg[1][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[1] [5]),
	.RN(FE_OFN588_n_584),
	.SE(n_579),
	.SI(\reg_file[1] [5]));
   SDFFRHQX1 \reg_file_reg[2][5]  (.CK(clk),
	.D(\reg_file[2] [5]),
	.Q(\reg_file[2] [5]),
	.RN(FE_OFN588_n_584),
	.SE(n_577),
	.SI(n_583));
   SDFFRHQX1 \reg_file_reg[3][5]  (.CK(clk),
	.D(\reg_file[3] [5]),
	.Q(\reg_file[3] [5]),
	.RN(FE_OFN588_n_584),
	.SE(n_576),
	.SI(n_583));
   SDFFRHQX1 \reg_file_reg[0][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[0] [5]),
	.RN(FE_OFN588_n_584),
	.SE(n_581),
	.SI(\reg_file[0] [5]));
   SDFFRHQX1 \reg_file_reg[5][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[5] [5]),
	.RN(FE_OFN588_n_584),
	.SE(n_582),
	.SI(\reg_file[5] [5]));
   SDFFRHQX1 \reg_file_reg[6][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[6] [5]),
	.RN(FE_OFN588_n_584),
	.SE(n_574),
	.SI(\reg_file[6] [5]));
   SDFFRHQX1 \reg_file_reg[7][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[7] [5]),
	.RN(FE_OFN588_n_584),
	.SE(n_573),
	.SI(\reg_file[7] [5]));
   SDFFRHQX1 \reg_file_reg[12][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[12] [5]),
	.RN(n_584),
	.SE(n_567),
	.SI(\reg_file[12] [5]));
   SDFFRHQX1 \reg_file_reg[9][5]  (.CK(clk),
	.D(\reg_file[9] [5]),
	.Q(\reg_file[9] [5]),
	.RN(n_584),
	.SE(n_570),
	.SI(n_583));
   SDFFRHQX1 \reg_file_reg[10][5]  (.CK(clk),
	.D(\reg_file[10] [5]),
	.Q(\reg_file[10] [5]),
	.RN(n_584),
	.SE(n_569),
	.SI(n_583));
   SDFFRHQX1 \reg_file_reg[11][5]  (.CK(clk),
	.D(\reg_file[11] [5]),
	.Q(\reg_file[11] [5]),
	.RN(n_584),
	.SE(n_568),
	.SI(n_583));
   SDFFRHQX1 \reg_file_reg[8][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[8] [5]),
	.RN(n_584),
	.SE(n_571),
	.SI(\reg_file[8] [5]));
   SDFFRHQX1 \reg_file_reg[13][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[13] [5]),
	.RN(n_584),
	.SE(n_566),
	.SI(\reg_file[13] [5]));
   SDFFRHQX1 \reg_file_reg[14][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[14] [5]),
	.RN(n_584),
	.SE(n_565),
	.SI(\reg_file[14] [5]));
   SDFFRHQX1 \reg_file_reg[15][5]  (.CK(clk),
	.D(n_583),
	.Q(\reg_file[15] [5]),
	.RN(n_584),
	.SE(n_572),
	.SI(\reg_file[15] [5]));
   SDFFRHQX1 \reg_file_reg[5][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[5] [6]),
	.RN(FE_OFN588_n_584),
	.SE(n_582),
	.SI(\reg_file[5] [6]));
   SDFFRHQX1 \reg_file_reg[0][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[0] [7]),
	.RN(FE_OFN588_n_584),
	.SE(n_581),
	.SI(\reg_file[0] [7]));
   SDFFRHQX1 \reg_file_reg[1][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[1] [6]),
	.RN(FE_OFN588_n_584),
	.SE(n_579),
	.SI(\reg_file[1] [6]));
   SDFFRHQX1 \reg_file_reg[1][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[1] [7]),
	.RN(FE_OFN588_n_584),
	.SE(n_579),
	.SI(\reg_file[1] [7]));
   SDFFRHQX1 \reg_file_reg[2][6]  (.CK(clk),
	.D(\reg_file[2] [6]),
	.Q(\reg_file[2] [6]),
	.RN(FE_OFN588_n_584),
	.SE(n_577),
	.SI(n_580));
   SDFFRHQX1 \reg_file_reg[3][6]  (.CK(clk),
	.D(\reg_file[3] [6]),
	.Q(\reg_file[3] [6]),
	.RN(FE_OFN588_n_584),
	.SE(n_576),
	.SI(n_580));
   SDFFRHQX1 \reg_file_reg[2][7]  (.CK(clk),
	.D(\reg_file[2] [7]),
	.Q(\reg_file[2] [7]),
	.RN(FE_OFN588_n_584),
	.SE(n_577),
	.SI(n_578));
   SDFFRHQX1 \reg_file_reg[3][7]  (.CK(clk),
	.D(\reg_file[3] [7]),
	.Q(\reg_file[3] [7]),
	.RN(FE_OFN588_n_584),
	.SE(n_576),
	.SI(n_578));
   SDFFRHQX1 \reg_file_reg[4][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[4] [6]),
	.RN(FE_OFN588_n_584),
	.SE(n_575),
	.SI(\reg_file[4] [6]));
   SDFFRHQX1 \reg_file_reg[6][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[6] [6]),
	.RN(FE_OFN588_n_584),
	.SE(n_574),
	.SI(\reg_file[6] [6]));
   SDFFRHQX1 \reg_file_reg[6][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[6] [7]),
	.RN(FE_OFN588_n_584),
	.SE(n_574),
	.SI(\reg_file[6] [7]));
   SDFFRHQX1 \reg_file_reg[4][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[4] [7]),
	.RN(FE_OFN588_n_584),
	.SE(n_575),
	.SI(\reg_file[4] [7]));
   SDFFRHQX1 \reg_file_reg[5][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[5] [7]),
	.RN(FE_OFN588_n_584),
	.SE(n_582),
	.SI(\reg_file[5] [7]));
   SDFFRHQX1 \reg_file_reg[7][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[7] [6]),
	.RN(FE_OFN588_n_584),
	.SE(n_573),
	.SI(\reg_file[7] [6]));
   SDFFRHQX1 \reg_file_reg[7][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[7] [7]),
	.RN(FE_OFN588_n_584),
	.SE(n_573),
	.SI(\reg_file[7] [7]));
   SDFFRHQX1 \reg_file_reg[0][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[0] [6]),
	.RN(FE_OFN588_n_584),
	.SE(n_581),
	.SI(\reg_file[0] [6]));
   SDFFRHQX1 \reg_file_reg[15][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[15] [7]),
	.RN(n_584),
	.SE(n_572),
	.SI(\reg_file[15] [7]));
   SDFFRHQX1 \reg_file_reg[8][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[8] [6]),
	.RN(n_584),
	.SE(n_571),
	.SI(\reg_file[8] [6]));
   SDFFRHQX1 \reg_file_reg[9][6]  (.CK(clk),
	.D(\reg_file[9] [6]),
	.Q(\reg_file[9] [6]),
	.RN(n_584),
	.SE(n_570),
	.SI(n_580));
   SDFFRHQX1 \reg_file_reg[10][6]  (.CK(clk),
	.D(\reg_file[10] [6]),
	.Q(\reg_file[10] [6]),
	.RN(n_584),
	.SE(n_569),
	.SI(n_580));
   SDFFRHQX1 \reg_file_reg[10][7]  (.CK(clk),
	.D(\reg_file[10] [7]),
	.Q(\reg_file[10] [7]),
	.RN(n_584),
	.SE(n_569),
	.SI(n_578));
   SDFFRHQX1 \reg_file_reg[11][6]  (.CK(clk),
	.D(\reg_file[11] [6]),
	.Q(\reg_file[11] [6]),
	.RN(n_584),
	.SE(n_568),
	.SI(n_580));
   SDFFRHQX1 \reg_file_reg[9][7]  (.CK(clk),
	.D(\reg_file[9] [7]),
	.Q(\reg_file[9] [7]),
	.RN(n_584),
	.SE(n_570),
	.SI(n_578));
   SDFFRHQX1 \reg_file_reg[11][7]  (.CK(clk),
	.D(\reg_file[11] [7]),
	.Q(\reg_file[11] [7]),
	.RN(n_584),
	.SE(n_568),
	.SI(n_578));
   SDFFRHQX1 \reg_file_reg[12][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[12] [6]),
	.RN(n_584),
	.SE(n_567),
	.SI(\reg_file[12] [6]));
   SDFFRHQX1 \reg_file_reg[12][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[12] [7]),
	.RN(n_584),
	.SE(n_567),
	.SI(\reg_file[12] [7]));
   SDFFRHQX1 \reg_file_reg[13][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[13] [6]),
	.RN(n_584),
	.SE(n_566),
	.SI(\reg_file[13] [6]));
   SDFFRHQX1 \reg_file_reg[13][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[13] [7]),
	.RN(n_584),
	.SE(n_566),
	.SI(\reg_file[13] [7]));
   SDFFRHQX1 \reg_file_reg[14][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[14] [6]),
	.RN(n_584),
	.SE(n_565),
	.SI(\reg_file[14] [6]));
   SDFFRHQX1 \reg_file_reg[14][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[14] [7]),
	.RN(n_584),
	.SE(n_565),
	.SI(\reg_file[14] [7]));
   SDFFRHQX1 \reg_file_reg[15][6]  (.CK(clk),
	.D(n_580),
	.Q(\reg_file[15] [6]),
	.RN(n_584),
	.SE(n_572),
	.SI(\reg_file[15] [6]));
   SDFFRHQX1 \reg_file_reg[8][7]  (.CK(clk),
	.D(n_578),
	.Q(\reg_file[8] [7]),
	.RN(n_584),
	.SE(n_571),
	.SI(\reg_file[8] [7]));
   SDFFRHQX1 \reg_file_reg[6][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[6] [4]),
	.RN(FE_OFN588_n_584),
	.SE(n_574),
	.SI(\reg_file[6] [4]));
   SDFFRHQX1 \reg_file_reg[1][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[1] [3]),
	.RN(FE_OFN588_n_584),
	.SE(n_579),
	.SI(\reg_file[1] [3]));
   SDFFRHQX1 \reg_file_reg[1][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[1] [4]),
	.RN(FE_OFN588_n_584),
	.SE(n_579),
	.SI(\reg_file[1] [4]));
   SDFFRHQX1 \reg_file_reg[14][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[14] [3]),
	.RN(FE_OFN588_n_584),
	.SE(n_565),
	.SI(\reg_file[14] [3]));
   SDFFRHQX1 \reg_file_reg[2][4]  (.CK(clk),
	.D(\reg_file[2] [4]),
	.Q(\reg_file[2] [4]),
	.RN(FE_OFN588_n_584),
	.SE(n_577),
	.SI(n_564));
   SDFFRHQX1 \reg_file_reg[2][3]  (.CK(clk),
	.D(\reg_file[2] [3]),
	.Q(\reg_file[2] [3]),
	.RN(FE_OFN588_n_584),
	.SE(n_577),
	.SI(n_563));
   SDFFRHQX1 \reg_file_reg[3][3]  (.CK(clk),
	.D(\reg_file[3] [3]),
	.Q(\reg_file[3] [3]),
	.RN(FE_OFN588_n_584),
	.SE(n_576),
	.SI(n_563));
   SDFFRHQX1 \reg_file_reg[12][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[12] [3]),
	.RN(FE_OFN588_n_584),
	.SE(n_567),
	.SI(\reg_file[12] [3]));
   SDFFRHQX1 \reg_file_reg[3][4]  (.CK(clk),
	.D(\reg_file[3] [4]),
	.Q(\reg_file[3] [4]),
	.RN(FE_OFN588_n_584),
	.SE(n_576),
	.SI(n_564));
   SDFFRHQX1 \reg_file_reg[4][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[4] [3]),
	.RN(n_584),
	.SE(n_575),
	.SI(\reg_file[4] [3]));
   SDFFRHQX1 \reg_file_reg[4][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[4] [4]),
	.RN(FE_OFN588_n_584),
	.SE(n_575),
	.SI(\reg_file[4] [4]));
   SDFFRHQX1 \reg_file_reg[10][3]  (.CK(clk),
	.D(\reg_file[10] [3]),
	.Q(\reg_file[10] [3]),
	.RN(n_584),
	.SE(n_569),
	.SI(n_563));
   SDFFRHQX1 \reg_file_reg[5][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[5] [3]),
	.RN(n_584),
	.SE(n_582),
	.SI(\reg_file[5] [3]));
   SDFFRHQX1 \reg_file_reg[5][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[5] [4]),
	.RN(FE_OFN588_n_584),
	.SE(n_582),
	.SI(\reg_file[5] [4]));
   SDFFRHQX1 \reg_file_reg[6][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[6] [3]),
	.RN(n_584),
	.SE(n_574),
	.SI(\reg_file[6] [3]));
   SDFFRHQX1 \reg_file_reg[8][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[8] [3]),
	.RN(n_584),
	.SE(n_571),
	.SI(\reg_file[8] [3]));
   SDFFRHQX1 \reg_file_reg[8][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[8] [4]),
	.RN(n_584),
	.SE(n_571),
	.SI(\reg_file[8] [4]));
   SDFFRHQX1 \reg_file_reg[7][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[7] [4]),
	.RN(FE_OFN588_n_584),
	.SE(n_573),
	.SI(\reg_file[7] [4]));
   SDFFRHQX1 \reg_file_reg[0][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[0] [3]),
	.RN(FE_OFN588_n_584),
	.SE(n_581),
	.SI(\reg_file[0] [3]));
   SDFFRHQX1 \reg_file_reg[15][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[15] [3]),
	.RN(FE_OFN588_n_584),
	.SE(n_572),
	.SI(\reg_file[15] [3]));
   SDFFRHQX1 \reg_file_reg[9][3]  (.CK(clk),
	.D(\reg_file[9] [3]),
	.Q(\reg_file[9] [3]),
	.RN(n_584),
	.SE(n_570),
	.SI(n_563));
   SDFFRHQX1 \reg_file_reg[9][4]  (.CK(clk),
	.D(\reg_file[9] [4]),
	.Q(\reg_file[9] [4]),
	.RN(n_584),
	.SE(n_570),
	.SI(n_564));
   SDFFRHQX1 \reg_file_reg[0][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[0] [4]),
	.RN(FE_OFN588_n_584),
	.SE(n_581),
	.SI(\reg_file[0] [4]));
   SDFFRHQX1 \reg_file_reg[10][4]  (.CK(clk),
	.D(\reg_file[10] [4]),
	.Q(\reg_file[10] [4]),
	.RN(n_584),
	.SE(n_569),
	.SI(n_564));
   SDFFRHQX1 \reg_file_reg[11][3]  (.CK(clk),
	.D(\reg_file[11] [3]),
	.Q(\reg_file[11] [3]),
	.RN(n_584),
	.SE(n_568),
	.SI(n_563));
   SDFFRHQX1 \reg_file_reg[11][4]  (.CK(clk),
	.D(\reg_file[11] [4]),
	.Q(\reg_file[11] [4]),
	.RN(n_584),
	.SE(n_568),
	.SI(n_564));
   SDFFRHQX1 \reg_file_reg[12][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[12] [4]),
	.RN(n_584),
	.SE(n_567),
	.SI(\reg_file[12] [4]));
   SDFFRHQX1 \reg_file_reg[13][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[13] [4]),
	.RN(n_584),
	.SE(n_566),
	.SI(\reg_file[13] [4]));
   SDFFRHQX1 \reg_file_reg[13][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[13] [3]),
	.RN(n_584),
	.SE(n_566),
	.SI(\reg_file[13] [3]));
   SDFFRHQX1 \reg_file_reg[14][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[14] [4]),
	.RN(n_584),
	.SE(n_565),
	.SI(\reg_file[14] [4]));
   SDFFRHQX1 \reg_file_reg[15][4]  (.CK(clk),
	.D(n_564),
	.Q(\reg_file[15] [4]),
	.RN(n_584),
	.SE(n_572),
	.SI(\reg_file[15] [4]));
   SDFFRHQX1 \reg_file_reg[7][3]  (.CK(clk),
	.D(n_563),
	.Q(\reg_file[7] [3]),
	.RN(FE_OFN588_n_584),
	.SE(n_573),
	.SI(\reg_file[7] [3]));
   OR2X1 g20713__2398 (.A(n_561),
	.B(n_559),
	.Y(n_583));
   SDFFRHQX1 \reg_file_reg[7][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[7] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_573),
	.SI(\reg_file[7] [2]));
   SDFFRHQX1 \reg_file_reg[1][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[1] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_579),
	.SI(\reg_file[1] [2]));
   SDFFRHQX1 \reg_file_reg[13][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[13] [2]),
	.RN(n_584),
	.SE(n_566),
	.SI(\reg_file[13] [2]));
   SDFFRHQX1 \reg_file_reg[9][2]  (.CK(clk),
	.D(\reg_file[9] [2]),
	.Q(\reg_file[9] [2]),
	.RN(n_584),
	.SE(n_570),
	.SI(n_562));
   SDFFRHQX1 \reg_file_reg[2][2]  (.CK(clk),
	.D(\reg_file[2] [2]),
	.Q(\reg_file[2] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_577),
	.SI(n_562));
   SDFFRHQX1 \reg_file_reg[3][2]  (.CK(clk),
	.D(\reg_file[3] [2]),
	.Q(\reg_file[3] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_576),
	.SI(n_562));
   SDFFRHQX1 \reg_file_reg[4][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[4] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_575),
	.SI(\reg_file[4] [2]));
   SDFFRHQX1 \reg_file_reg[6][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[6] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_574),
	.SI(\reg_file[6] [2]));
   SDFFRHQX1 \reg_file_reg[5][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[5] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_582),
	.SI(\reg_file[5] [2]));
   SDFFRHQX1 \reg_file_reg[8][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[8] [2]),
	.RN(n_584),
	.SE(n_571),
	.SI(\reg_file[8] [2]));
   SDFFRHQX1 \reg_file_reg[11][2]  (.CK(clk),
	.D(\reg_file[11] [2]),
	.Q(\reg_file[11] [2]),
	.RN(n_584),
	.SE(n_568),
	.SI(n_562));
   SDFFRHQX1 \reg_file_reg[12][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[12] [2]),
	.RN(n_584),
	.SE(n_567),
	.SI(\reg_file[12] [2]));
   SDFFRHQX1 \reg_file_reg[0][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[0] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_581),
	.SI(\reg_file[0] [2]));
   SDFFRHQX1 \reg_file_reg[14][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[14] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_565),
	.SI(\reg_file[14] [2]));
   SDFFRHQX1 \reg_file_reg[15][2]  (.CK(clk),
	.D(n_562),
	.Q(\reg_file[15] [2]),
	.RN(FE_OFN588_n_584),
	.SE(n_572),
	.SI(\reg_file[15] [2]));
   SDFFRHQX1 \reg_file_reg[10][2]  (.CK(clk),
	.D(\reg_file[10] [2]),
	.Q(\reg_file[10] [2]),
	.RN(n_584),
	.SE(n_569),
	.SI(n_562));
   NAND2XL g20711__5107 (.A(n_557),
	.B(n_560),
	.Y(n_578));
   NAND2XL g20712__6260 (.A(n_556),
	.B(n_607),
	.Y(n_580));
   OAI21X1 g20716__4319 (.A0(n_449),
	.A1(n_549),
	.B0(n_467),
	.Y(n_561));
   NOR2XL g20715__8428 (.A(n_543),
	.B(n_552),
	.Y(n_560));
   AOI21X1 g20717__5526 (.A0(n_547),
	.A1(n_538),
	.B0(n_450),
	.Y(n_559));
   AO21X1 g20720__3680 (.A0(n_554),
	.A1(n_526),
	.B0(n_555),
	.Y(n_564));
   AO21X1 g20719__1617 (.A0(n_599),
	.A1(n_519),
	.B0(n_553),
	.Y(n_563));
   OAI2BB1X1 g20714__2802 (.A0N(n_601),
	.A1N(n_542),
	.B0(n_550),
	.Y(n_557));
   NOR2XL g20731__1705 (.A(n_534),
	.B(n_544),
	.Y(n_556));
   OAI21X1 g20732__5122 (.A0(n_554),
	.A1(n_522),
	.B0(n_475),
	.Y(n_555));
   OAI21X1 g20733__8246 (.A0(n_551),
	.A1(n_520),
	.B0(n_476),
	.Y(n_553));
   OAI31X1 g20734__7098 (.A0(n_551),
	.A1(n_550),
	.A2(n_540),
	.B0(n_454),
	.Y(n_552));
   NOR2BXL g20755__6131 (.AN(n_531),
	.B(n_527),
	.Y(n_549));
   SDFFRHQX1 \reg_file_reg[8][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[8] [1]),
	.RN(n_584),
	.SE(n_571),
	.SI(\reg_file[8] [1]));
   SDFFRHQX1 \reg_file_reg[10][1]  (.CK(clk),
	.D(\reg_file[10] [1]),
	.Q(\reg_file[10] [1]),
	.RN(n_584),
	.SE(n_569),
	.SI(n_548));
   SDFFRHQX1 \reg_file_reg[4][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[4] [1]),
	.RN(FE_OFN588_n_584),
	.SE(n_575),
	.SI(\reg_file[4] [1]));
   SDFFRHQX1 \reg_file_reg[0][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[0] [1]),
	.RN(FE_OFN588_n_584),
	.SE(n_581),
	.SI(\reg_file[0] [1]));
   SDFFRHQX1 \reg_file_reg[1][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[1] [1]),
	.RN(FE_OFN588_n_584),
	.SE(n_579),
	.SI(\reg_file[1] [1]));
   AO21X1 g20766__1881 (.A0(n_515),
	.A1(n_494),
	.B0(n_537),
	.Y(n_562));
   SDFFRHQX1 \reg_file_reg[9][1]  (.CK(clk),
	.D(\reg_file[9] [1]),
	.Q(\reg_file[9] [1]),
	.RN(n_584),
	.SE(n_570),
	.SI(n_548));
   SDFFRHQX1 \reg_file_reg[3][1]  (.CK(clk),
	.D(\reg_file[3] [1]),
	.Q(\reg_file[3] [1]),
	.RN(FE_OFN588_n_584),
	.SE(n_576),
	.SI(n_548));
   SDFFRHQX1 \reg_file_reg[5][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[5] [1]),
	.RN(FE_OFN588_n_584),
	.SE(n_582),
	.SI(\reg_file[5] [1]));
   SDFFRHQX1 \reg_file_reg[6][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[6] [1]),
	.RN(FE_OFN588_n_584),
	.SE(n_574),
	.SI(\reg_file[6] [1]));
   SDFFRHQX1 \reg_file_reg[7][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[7] [1]),
	.RN(FE_OFN588_n_584),
	.SE(n_573),
	.SI(\reg_file[7] [1]));
   SDFFRHQX1 \reg_file_reg[2][1]  (.CK(clk),
	.D(\reg_file[2] [1]),
	.Q(\reg_file[2] [1]),
	.RN(FE_OFN588_n_584),
	.SE(n_577),
	.SI(n_548));
   SDFFRHQX1 \reg_file_reg[14][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[14] [1]),
	.RN(n_584),
	.SE(n_565),
	.SI(\reg_file[14] [1]));
   SDFFRHQX1 \reg_file_reg[15][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[15] [1]),
	.RN(n_584),
	.SE(n_572),
	.SI(\reg_file[15] [1]));
   SDFFRHQX1 \reg_file_reg[11][1]  (.CK(clk),
	.D(\reg_file[11] [1]),
	.Q(\reg_file[11] [1]),
	.RN(n_584),
	.SE(n_568),
	.SI(n_548));
   SDFFRHQX1 \reg_file_reg[12][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[12] [1]),
	.RN(n_584),
	.SE(n_567),
	.SI(\reg_file[12] [1]));
   SDFFRHQX1 \reg_file_reg[13][1]  (.CK(clk),
	.D(n_548),
	.Q(\reg_file[13] [1]),
	.RN(n_584),
	.SE(n_566),
	.SI(\reg_file[13] [1]));
   NAND2XL g20757__5115 (.A(n_599),
	.B(n_530),
	.Y(n_547));
   OAI21X1 g20762__4733 (.A0(n_503),
	.A1(n_518),
	.B0(n_453),
	.Y(n_544));
   AOI211X1 g20754__6161 (.A0(n_504),
	.A1(n_602),
	.B0(n_533),
	.C0(n_550),
	.Y(n_543));
   NAND2XL g20756__9315 (.A(n_541),
	.B(n_540),
	.Y(n_542));
   OAI21X1 g20760__2883 (.A0(n_451),
	.A1(n_510),
	.B0(n_541),
	.Y(n_538));
   NAND2XL g20768__2346 (.A(n_482),
	.B(n_516),
	.Y(n_537));
   AOI211X1 g20761__7410 (.A0(n_502),
	.A1(n_517),
	.B0(n_533),
	.C0(n_532),
	.Y(n_534));
   AOI32X1 g20771__6417 (.A0(n_599),
	.A1(n_529),
	.A2(n_501),
	.B0(n_599),
	.B1(n_528),
	.Y(n_531));
   AOI21X1 g20769__5477 (.A0(n_529),
	.A1(n_525),
	.B0(n_528),
	.Y(n_530));
   AOI21XL g20770__2398 (.A0(n_509),
	.A1(n_497),
	.B0(n_440),
	.Y(n_527));
   OAI22X1 g20773__5107 (.A0(n_533),
	.A1(n_525),
	.B0(n_551),
	.B1(n_521),
	.Y(n_526));
   AOI22XL g20776__6260 (.A0(n_525),
	.A1(n_599),
	.B0(n_521),
	.B1(n_541),
	.Y(n_522));
   AOI21XL g20774__4319 (.A0(n_512),
	.A1(n_511),
	.B0(n_513),
	.Y(n_520));
   OAI21XL g20775__8428 (.A0(n_507),
	.A1(n_506),
	.B0(n_508),
	.Y(n_519));
   CLKINVX1 g20779 (.A(n_517),
	.Y(n_518));
   NAND2BX1 g20780__5526 (.AN(n_515),
	.B(n_499),
	.Y(n_516));
   OAI21X1 g20777__6783 (.A0(n_458),
	.A1(n_521),
	.B0(n_489),
	.Y(n_523));
   SDFFRHQX1 \reg_file_reg[4][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[4] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_575),
	.SI(\reg_file[4] [0]));
   SDFFRHQX1 \reg_file_reg[8][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[8] [0]),
	.RN(n_584),
	.SE(n_571),
	.SI(\reg_file[8] [0]));
   SDFFRHQX1 \reg_file_reg[12][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[12] [0]),
	.RN(n_584),
	.SE(n_567),
	.SI(\reg_file[12] [0]));
   SDFFRHQX1 \reg_file_reg[1][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[1] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_579),
	.SI(\reg_file[1] [0]));
   SDFFRHQX1 \reg_file_reg[0][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[0] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_581),
	.SI(\reg_file[0] [0]));
   AO21X1 g20787__1617 (.A0(n_495),
	.A1(n_485),
	.B0(n_496),
	.Y(n_548));
   OAI21X1 g20778__2802 (.A0(n_460),
	.A1(n_521),
	.B0(n_490),
	.Y(n_540));
   SDFFRHQX1 \reg_file_reg[5][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[5] [0]),
	.RN(n_584),
	.SE(n_582),
	.SI(\reg_file[5] [0]));
   SDFFRHQX1 \reg_file_reg[6][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[6] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_574),
	.SI(\reg_file[6] [0]));
   SDFFRHQX1 \reg_file_reg[7][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[7] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_573),
	.SI(\reg_file[7] [0]));
   SDFFRHQX1 \reg_file_reg[13][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[13] [0]),
	.RN(n_584),
	.SE(n_566),
	.SI(\reg_file[13] [0]));
   SDFFRHQX1 \reg_file_reg[14][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[14] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_565),
	.SI(\reg_file[14] [0]));
   SDFFRHQX1 \reg_file_reg[15][0]  (.CK(clk),
	.D(n_514),
	.Q(\reg_file[15] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_572),
	.SI(\reg_file[15] [0]));
   NOR2XL g20784__1705 (.A(n_512),
	.B(n_511),
	.Y(n_513));
   NOR2BX1 g20786__5122 (.AN(n_509),
	.B(n_521),
	.Y(n_510));
   NAND2XL g20781__8246 (.A(n_507),
	.B(n_506),
	.Y(n_508));
   OR2X1 g20783__6131 (.A(n_472),
	.B(n_500),
	.Y(n_517));
   NAND3X1 g20813__1881 (.A(n_599),
	.B(n_502),
	.C(n_532),
	.Y(n_503));
   OAI21X1 g20789__5115 (.A0(n_444),
	.A1(n_498),
	.B0(n_462),
	.Y(n_501));
   CLKINVX1 g20788 (.A(n_500),
	.Y(n_525));
   OAI22X1 g20795__7482 (.A0(n_551),
	.A1(n_492),
	.B0(n_533),
	.B1(n_498),
	.Y(n_499));
   INVXL g20794 (.A(n_521),
	.Y(n_497));
   OAI21XL g20790__4733 (.A0(n_495),
	.A1(n_486),
	.B0(n_491),
	.Y(n_496));
   OAI22X1 g20796__6161 (.A0(n_533),
	.A1(n_493),
	.B0(n_551),
	.B1(n_488),
	.Y(n_494));
   AOI21X1 g20791__9315 (.A0(n_479),
	.A1(n_493),
	.B0(n_481),
	.Y(n_506));
   AOI21X1 g20792__9945 (.A0(n_473),
	.A1(n_603),
	.B0(n_452),
	.Y(n_504));
   AOI21X1 g20793__2883 (.A0(n_443),
	.A1(n_493),
	.B0(n_461),
	.Y(n_500));
   AOI21X1 g20798__2346 (.A0(n_447),
	.A1(n_492),
	.B0(n_402),
	.Y(n_511));
   AOI21X1 g20799__1666 (.A0(n_421),
	.A1(n_492),
	.B0(n_463),
	.Y(n_521));
   DFFRHQX1 \data_out_reg[0]  (.CK(clk),
	.D(n_468),
	.Q(data_out[0]),
	.RN(FE_OFN588_n_584));
   DFFRHQX1 \data_out_reg[2]  (.CK(clk),
	.D(n_469),
	.Q(data_out[2]),
	.RN(n_584));
   AOI222XL g20812__7410 (.A0(n_480),
	.A1(data_in[1]),
	.B0(instruction[14]),
	.B1(n_436),
	.C0(n_600),
	.C1(n_401),
	.Y(n_491));
   DFFRHQX1 \data_out_reg[6]  (.CK(clk),
	.D(n_477),
	.Q(data_out[6]),
	.RN(FE_OFN588_n_584));
   DFFRHQX1 \data_out_reg[4]  (.CK(clk),
	.D(n_471),
	.Q(data_out[4]),
	.RN(FE_OFN588_n_584));
   DFFRHQX1 \data_out_reg[3]  (.CK(clk),
	.D(n_465),
	.Q(data_out[3]),
	.RN(n_584));
   DFFRHQX1 \data_out_reg[7]  (.CK(clk),
	.D(n_466),
	.Q(data_out[7]),
	.RN(n_584));
   DFFRHQX1 \data_out_reg[5]  (.CK(clk),
	.D(n_470),
	.Q(data_out[5]),
	.RN(FE_OFN588_n_584));
   DFFRHQX1 \data_out_reg[1]  (.CK(clk),
	.D(n_464),
	.Q(data_out[1]),
	.RN(FE_OFN588_n_584));
   AOI2BB1X1 g20797__6417 (.A0N(n_596),
	.A1N(n_489),
	.B0(n_597),
	.Y(n_490));
   OAI21X1 g20800__5477 (.A0(n_398),
	.A1(n_455),
	.B0(n_457),
	.Y(n_514));
   INVXL g20829 (.A(n_492),
	.Y(n_488));
   CLKINVX1 g20817 (.A(n_603),
	.Y(n_502));
   CLKINVX1 g20830 (.A(n_493),
	.Y(n_498));
   AOI22X1 g20831__2398 (.A0(n_541),
	.A1(n_484),
	.B0(n_599),
	.B1(n_378),
	.Y(n_486));
   OAI22XL g20834__5107 (.A0(n_484),
	.A1(n_551),
	.B0(n_378),
	.B1(n_533),
	.Y(n_485));
   AOI222XL g20809__6260 (.A0(instruction[14]),
	.A1(n_481),
	.B0(data_in[2]),
	.B1(n_480),
	.C0(n_479),
	.C1(n_600),
	.Y(n_482));
   NAND4BXL g20823__4319 (.AN(n_420),
	.B(n_332),
	.C(n_299),
	.D(n_386),
	.Y(n_477));
   AOI222XL g20814__8428 (.A0(instruction[14]),
	.A1(n_422),
	.B0(data_in[3]),
	.B1(n_480),
	.C0(n_411),
	.C1(n_600),
	.Y(n_476));
   AOI222XL g20815__5526 (.A0(instruction[14]),
	.A1(n_528),
	.B0(data_in[4]),
	.B1(n_480),
	.C0(n_529),
	.C1(n_600),
	.Y(n_475));
   NAND4BXL g20819__3680 (.AN(n_424),
	.B(n_346),
	.C(n_288),
	.D(n_387),
	.Y(n_471));
   NAND4BXL g20820__1617 (.AN(n_428),
	.B(n_360),
	.C(n_300),
	.D(n_382),
	.Y(n_470));
   NAND4BXL g20821__2802 (.AN(n_418),
	.B(n_338),
	.C(n_295),
	.D(n_408),
	.Y(n_469));
   NAND4BXL g20822__1705 (.AN(n_419),
	.B(n_328),
	.C(n_291),
	.D(n_409),
	.Y(n_468));
   AOI222XL g20810__5122 (.A0(instruction[14]),
	.A1(n_456),
	.B0(data_in[5]),
	.B1(n_480),
	.C0(n_441),
	.C1(n_600),
	.Y(n_467));
   NAND4BXL g20824__8246 (.AN(n_427),
	.B(n_348),
	.C(n_301),
	.D(n_415),
	.Y(n_466));
   NAND4BXL g20825__7098 (.AN(n_425),
	.B(n_327),
	.C(n_290),
	.D(n_414),
	.Y(n_465));
   NAND4BXL g20826__6131 (.AN(n_426),
	.B(n_344),
	.C(n_302),
	.D(n_383),
	.Y(n_464));
   OAI21X1 g20836__1881 (.A0(n_446),
	.A1(n_429),
	.B0(n_430),
	.Y(n_463));
   INVXL g20828 (.A(n_461),
	.Y(n_462));
   OR2XL g20832__5115 (.A(n_596),
	.B(n_458),
	.Y(n_460));
   AOI22X1 g20835__7482 (.A0(instruction[14]),
	.A1(n_378),
	.B0(data_in[0]),
	.B1(n_480),
	.Y(n_457));
   NAND2XL g20840__6161 (.A(n_435),
	.B(n_439),
	.Y(n_493));
   NAND2XL g20839__9315 (.A(n_448),
	.B(n_438),
	.Y(n_492));
   AOI21X1 g20833__9945 (.A0(instruction[13]),
	.A1(n_407),
	.B0(n_600),
	.Y(n_455));
   AOI221X1 g20816__2883 (.A0(data_in[7]),
	.A1(n_480),
	.B0(n_393),
	.B1(n_399),
	.C0(n_375),
	.Y(n_454));
   AOI222XL g20811__2346 (.A0(instruction[14]),
	.A1(n_452),
	.B0(data_in[6]),
	.B1(n_480),
	.C0(n_473),
	.C1(n_600),
	.Y(n_453));
   OAI21X1 g20838__1666 (.A0(n_432),
	.A1(n_451),
	.B0(n_434),
	.Y(n_489));
   OAI21X1 g20837__7410 (.A0(n_406),
	.A1(n_410),
	.B0(n_423),
	.Y(n_461));
   CLKINVX1 g20856 (.A(n_449),
	.Y(n_450));
   NAND2XL g20851__6417 (.A(n_437),
	.B(n_448),
	.Y(n_495));
   CLKINVX1 g20842 (.A(n_512),
	.Y(n_507));
   NAND2XL g20852__5477 (.A(n_447),
	.B(n_446),
	.Y(n_515));
   CLKINVX1 g20843 (.A(n_445),
	.Y(n_532));
   INVXL g20841 (.A(n_443),
	.Y(n_444));
   NAND2BXL g20845__5107 (.AN(n_451),
	.B(n_541),
	.Y(n_440));
   OAI21X1 g20846__6260 (.A0(n_405),
	.A1(n_404),
	.B0(n_378),
	.Y(n_439));
   NAND2XL g20847__4319 (.A(n_437),
	.B(n_403),
	.Y(n_438));
   NAND2XL g20848__8428 (.A(n_441),
	.B(n_529),
	.Y(n_472));
   INVXL g20869 (.A(n_435),
	.Y(n_436));
   NAND2XL g20850__5526 (.A(n_509),
	.B(n_434),
	.Y(n_458));
   NOR2XL g20855__6783 (.A(n_597),
	.B(n_596),
	.Y(n_445));
   NAND2BX1 g20849__3680 (.AN(n_451),
	.B(n_509),
	.Y(n_554));
   NAND2BX1 g20867__1617 (.AN(n_432),
	.B(n_434),
	.Y(n_449));
   NOR2BX1 g20854__2802 (.AN(n_430),
	.B(n_429),
	.Y(n_512));
   NAND4XL g20862__1705 (.A(n_342),
	.B(n_323),
	.C(n_304),
	.D(n_341),
	.Y(n_428));
   NAND4XL g20857__5122 (.A(n_293),
	.B(n_343),
	.C(n_292),
	.D(n_349),
	.Y(n_427));
   NAND4XL g20858__8246 (.A(n_312),
	.B(n_369),
	.C(n_316),
	.D(n_368),
	.Y(n_426));
   NAND4XL g20860__7098 (.A(n_358),
	.B(n_289),
	.C(n_313),
	.D(n_326),
	.Y(n_425));
   NAND4XL g20861__6131 (.A(n_367),
	.B(n_311),
	.C(n_324),
	.D(n_364),
	.Y(n_424));
   INVXL g20870 (.A(n_422),
	.Y(n_423));
   AOI22X1 g20863__1881 (.A0(n_417),
	.A1(n_381),
	.B0(n_416),
	.B1(n_396),
	.Y(n_421));
   NAND4XL g20864__5115 (.A(n_296),
	.B(n_333),
	.C(n_297),
	.D(n_345),
	.Y(n_420));
   NAND4XL g20865__7482 (.A(n_318),
	.B(n_359),
	.C(n_305),
	.D(n_331),
	.Y(n_419));
   NAND4XL g20866__4733 (.A(n_347),
	.B(n_303),
	.C(n_308),
	.D(n_334),
	.Y(n_418));
   AOI22X1 g20853__6161 (.A0(n_417),
	.A1(n_394),
	.B0(n_395),
	.B1(n_416),
	.Y(n_443));
   AOI221X1 g20898__9315 (.A0(\reg_file[11] [7]),
	.A1(n_413),
	.B0(\reg_file[10] [7]),
	.B1(n_412),
	.C0(n_330),
	.Y(n_415));
   AOI221X1 g20897__9945 (.A0(\reg_file[11] [3]),
	.A1(n_413),
	.B0(\reg_file[10] [3]),
	.B1(n_412),
	.C0(n_329),
	.Y(n_414));
   INVXL g20871 (.A(n_410),
	.Y(n_411));
   AOI221X1 g20899__2883 (.A0(\reg_file[2] [0]),
	.A1(n_321),
	.B0(\reg_file[3] [0]),
	.B1(n_320),
	.C0(n_339),
	.Y(n_409));
   AOI221X1 g20901__2346 (.A0(\reg_file[11] [2]),
	.A1(n_413),
	.B0(\reg_file[10] [2]),
	.B1(n_412),
	.C0(n_340),
	.Y(n_408));
   CLKINVX1 g20872 (.A(n_406),
	.Y(n_481));
   NAND2XL g20877__1666 (.A(n_405),
	.B(n_404),
	.Y(n_435));
   CLKINVX1 g20891 (.A(n_403),
	.Y(n_484));
   CLKINVX1 g20892 (.A(n_402),
	.Y(n_446));
   NAND2XL g20905__7410 (.A(n_400),
	.B(n_404),
	.Y(n_448));
   NAND2XL g20878__6417 (.A(n_400),
	.B(n_397),
	.Y(n_401));
   OAI21X1 g20859__5477 (.A0(n_2),
	.A1(n_392),
	.B0(n_374),
	.Y(n_399));
   NOR2XL g20873__2398 (.A(n_379),
	.B(n_337),
	.Y(n_398));
   NAND2XL g20880__5107 (.A(n_397),
	.B(n_405),
	.Y(n_437));
   NOR2XL g20881__6260 (.A(n_390),
	.B(n_391),
	.Y(n_456));
   NAND2BX1 g20888__4319 (.AN(n_416),
	.B(n_396),
	.Y(n_406));
   NAND2XL g20883__8428 (.A(n_416),
	.B(n_395),
	.Y(n_479));
   AND2X1 g20884__5526 (.A(n_417),
	.B(n_394),
	.Y(n_410));
   NOR2XL g20879__6783 (.A(n_417),
	.B(n_394),
	.Y(n_422));
   MXI2XL g20868__3680 (.A(n_393),
	.B(n_310),
	.S0(n_392),
	.Y(n_550));
   NAND2XL g20887__2802 (.A(n_391),
	.B(n_380),
	.Y(n_434));
   NAND2XL g20882__1705 (.A(n_390),
	.B(n_391),
	.Y(n_441));
   NAND2XL g20890__5122 (.A(n_389),
	.B(n_388),
	.Y(n_529));
   NOR2XL g20889__8246 (.A(n_389),
	.B(n_388),
	.Y(n_528));
   AOI221X1 g20896__7098 (.A0(\reg_file[6] [4]),
	.A1(n_385),
	.B0(\reg_file[7] [4]),
	.B1(n_384),
	.C0(n_317),
	.Y(n_387));
   AOI221X1 g20900__6131 (.A0(\reg_file[6] [6]),
	.A1(n_385),
	.B0(\reg_file[7] [6]),
	.B1(n_384),
	.C0(n_298),
	.Y(n_386));
   AOI221X1 g20902__1881 (.A0(\reg_file[6] [1]),
	.A1(n_385),
	.B0(\reg_file[7] [1]),
	.B1(n_384),
	.C0(n_322),
	.Y(n_383));
   AOI221X1 g20903__5115 (.A0(\reg_file[6] [5]),
	.A1(n_385),
	.B0(\reg_file[7] [5]),
	.B1(n_384),
	.C0(n_294),
	.Y(n_382));
   OR2X1 g20904__7482 (.A(n_417),
	.B(n_381),
	.Y(n_430));
   NOR2XL g20906__4733 (.A(n_391),
	.B(n_380),
	.Y(n_432));
   NAND3X1 g20908__6161 (.A(n_336),
	.B(n_335),
	.C(n_379),
	.Y(n_403));
   NAND2XL g20909__9315 (.A(n_416),
	.B(n_396),
	.Y(n_447));
   AND2X1 g20910__9945 (.A(n_417),
	.B(n_381),
	.Y(n_429));
   NOR2XL g20911__2883 (.A(n_416),
	.B(n_396),
	.Y(n_402));
   CLKINVX1 g20895 (.A(n_378),
	.Y(n_407));
   NOR2XL g20912__2346 (.A(n_388),
	.B(n_377),
	.Y(n_451));
   NAND2XL g20907__1666 (.A(n_388),
	.B(n_377),
	.Y(n_509));
   NAND2XL g20957__7410 (.A(n_352),
	.B(n_376),
	.Y(n_581));
   NAND2XL g20958__6417 (.A(n_355),
	.B(n_376),
	.Y(n_571));
   NAND2XL g20966__5477 (.A(n_354),
	.B(n_376),
	.Y(n_579));
   NOR2XL g20874__2398 (.A(n_374),
	.B(n_392),
	.Y(n_375));
   NOR2XL g20876__6260 (.A(n_373),
	.B(n_372),
	.Y(n_452));
   AOI22X1 g20913__4319 (.A0(n_265),
	.A1(n_250),
	.B0(n_274),
	.B1(n_278),
	.Y(n_378));
   NAND2XL g20885__8428 (.A(n_373),
	.B(n_372),
	.Y(n_473));
   CLKINVX1 g20917 (.A(n_397),
	.Y(n_404));
   NOR2XL g20963__5526 (.A(n_246),
	.B(n_371),
	.Y(n_569));
   NOR2XL g20960__6783 (.A(n_370),
	.B(n_371),
	.Y(n_568));
   NOR2XL g20952__3680 (.A(n_247),
	.B(n_371),
	.Y(n_576));
   NOR2XL g20965__1617 (.A(n_243),
	.B(n_371),
	.Y(n_577));
   NOR2XL g20951__2802 (.A(n_370),
	.B(n_325),
	.Y(n_570));
   AOI22X1 g20931__1705 (.A0(\reg_file[12] [1]),
	.A1(n_366),
	.B0(\reg_file[13] [1]),
	.B1(n_365),
	.Y(n_369));
   AOI22X1 g20936__5122 (.A0(\reg_file[14] [1]),
	.A1(n_363),
	.B0(\reg_file[15] [1]),
	.B1(n_362),
	.Y(n_368));
   AOI22XL g20927__8246 (.A0(n_366),
	.A1(\reg_file[12] [4]),
	.B0(n_365),
	.B1(\reg_file[13] [4]),
	.Y(n_367));
   AOI22X1 g20930__7098 (.A0(\reg_file[14] [4]),
	.A1(n_363),
	.B0(\reg_file[15] [4]),
	.B1(n_362),
	.Y(n_364));
   AOI22X1 g20933__6131 (.A0(\reg_file[4] [5]),
	.A1(n_357),
	.B0(\reg_file[5] [5]),
	.B1(n_356),
	.Y(n_360));
   AOI22X1 g20934__1881 (.A0(\reg_file[12] [0]),
	.A1(n_366),
	.B0(\reg_file[13] [0]),
	.B1(n_365),
	.Y(n_359));
   AOI22XL g20935__5115 (.A0(n_357),
	.A1(\reg_file[4] [3]),
	.B0(n_356),
	.B1(\reg_file[5] [3]),
	.Y(n_358));
   CLKINVX1 g20915 (.A(n_377),
	.Y(n_389));
   CLKINVX1 g20916 (.A(n_380),
	.Y(n_390));
   CLKINVX1 g20918 (.A(n_405),
	.Y(n_400));
   CLKINVX1 g20919 (.A(n_396),
	.Y(n_395));
   CLKINVX1 g20922 (.A(n_394),
	.Y(n_381));
   AND2X1 g20944__7482 (.A(n_284),
	.B(n_286),
	.Y(n_397));
   NOR2XL g20940__4733 (.A(n_605),
	.B(n_604),
	.Y(n_388));
   AND2X1 g20941__6161 (.A(n_277),
	.B(n_276),
	.Y(n_391));
   AND2X1 g20938__9315 (.A(n_282),
	.B(n_283),
	.Y(n_417));
   AND2X1 g20943__9945 (.A(n_285),
	.B(n_281),
	.Y(n_416));
   NAND2XL g20954__2883 (.A(n_355),
	.B(n_353),
	.Y(n_565));
   NAND2XL g20955__2346 (.A(n_354),
	.B(n_353),
	.Y(n_573));
   NAND2XL g20956__1666 (.A(n_351),
	.B(n_353),
	.Y(n_572));
   NAND2XL g20959__7410 (.A(n_352),
	.B(n_350),
	.Y(n_575));
   NAND2XL g20961__6417 (.A(n_351),
	.B(n_350),
	.Y(n_566));
   NAND2XL g20953__5477 (.A(n_352),
	.B(n_353),
	.Y(n_574));
   AOI22X1 g20992__2398 (.A0(\reg_file[6] [7]),
	.A1(n_385),
	.B0(\reg_file[7] [7]),
	.B1(n_384),
	.Y(n_349));
   AOI22X1 g20977__5107 (.A0(\reg_file[14] [7]),
	.A1(n_363),
	.B0(\reg_file[15] [7]),
	.B1(n_362),
	.Y(n_348));
   AOI22XL g20976__6260 (.A0(n_357),
	.A1(\reg_file[4] [2]),
	.B0(n_356),
	.B1(\reg_file[5] [2]),
	.Y(n_347));
   AOI22X1 g20967__4319 (.A0(\reg_file[4] [4]),
	.A1(n_357),
	.B0(\reg_file[5] [4]),
	.B1(n_356),
	.Y(n_346));
   AOI22X1 g20968__8428 (.A0(\reg_file[14] [6]),
	.A1(n_363),
	.B0(\reg_file[15] [6]),
	.B1(n_362),
	.Y(n_345));
   AOI22X1 g20974__5526 (.A0(\reg_file[4] [1]),
	.A1(n_357),
	.B0(\reg_file[5] [1]),
	.B1(n_356),
	.Y(n_344));
   AOI22X1 g20970__6783 (.A0(\reg_file[4] [7]),
	.A1(n_357),
	.B0(\reg_file[5] [7]),
	.B1(n_356),
	.Y(n_343));
   AOI22XL g20975__3680 (.A0(n_366),
	.A1(\reg_file[12] [5]),
	.B0(n_365),
	.B1(\reg_file[13] [5]),
	.Y(n_342));
   AOI22X1 g20983__1617 (.A0(\reg_file[14] [5]),
	.A1(n_363),
	.B0(\reg_file[15] [5]),
	.B1(n_362),
	.Y(n_341));
   AO22XL g20986__2802 (.A0(\reg_file[12] [2]),
	.A1(n_366),
	.B0(\reg_file[13] [2]),
	.B1(n_365),
	.Y(n_340));
   AO22XL g20987__1705 (.A0(\reg_file[4] [0]),
	.A1(n_357),
	.B0(\reg_file[5] [0]),
	.B1(n_356),
	.Y(n_339));
   AOI22X1 g20988__5122 (.A0(\reg_file[14] [2]),
	.A1(n_363),
	.B0(\reg_file[15] [2]),
	.B1(n_362),
	.Y(n_338));
   NAND2XL g21009__8246 (.A(n_336),
	.B(n_335),
	.Y(n_337));
   AOI22X1 g20993__7098 (.A0(\reg_file[6] [2]),
	.A1(n_385),
	.B0(\reg_file[7] [2]),
	.B1(n_384),
	.Y(n_334));
   AOI22X1 g20994__6131 (.A0(\reg_file[12] [6]),
	.A1(n_366),
	.B0(\reg_file[13] [6]),
	.B1(n_365),
	.Y(n_333));
   AOI22X1 g20996__1881 (.A0(\reg_file[4] [6]),
	.A1(n_357),
	.B0(\reg_file[5] [6]),
	.B1(n_356),
	.Y(n_332));
   AOI22X1 g20997__5115 (.A0(\reg_file[14] [0]),
	.A1(n_363),
	.B0(\reg_file[15] [0]),
	.B1(n_362),
	.Y(n_331));
   AO22XL g20998__7482 (.A0(\reg_file[12] [7]),
	.A1(n_366),
	.B0(\reg_file[13] [7]),
	.B1(n_365),
	.Y(n_330));
   AO22XL g21000__4733 (.A0(\reg_file[12] [3]),
	.A1(n_366),
	.B0(\reg_file[13] [3]),
	.B1(n_365),
	.Y(n_329));
   AOI22X1 g21003__6161 (.A0(\reg_file[6] [0]),
	.A1(n_385),
	.B0(\reg_file[7] [0]),
	.B1(n_384),
	.Y(n_328));
   AOI22X1 g21004__9315 (.A0(\reg_file[14] [3]),
	.A1(n_363),
	.B0(\reg_file[15] [3]),
	.B1(n_362),
	.Y(n_327));
   AOI22X1 g21006__9945 (.A0(\reg_file[6] [3]),
	.A1(n_385),
	.B0(\reg_file[7] [3]),
	.B1(n_384),
	.Y(n_326));
   INVXL g21011 (.A(n_325),
	.Y(n_376));
   NAND2XL g20964__2883 (.A(n_354),
	.B(n_350),
	.Y(n_582));
   NAND2XL g20962__2346 (.A(n_355),
	.B(n_350),
	.Y(n_567));
   AOI22X1 g20926__1666 (.A0(\reg_file[8] [4]),
	.A1(n_315),
	.B0(\reg_file[9] [4]),
	.B1(n_314),
	.Y(n_324));
   AOI22X1 g20973__7410 (.A0(\reg_file[10] [5]),
	.A1(n_412),
	.B0(\reg_file[11] [5]),
	.B1(n_413),
	.Y(n_323));
   AO22XL g20969__6417 (.A0(\reg_file[2] [1]),
	.A1(n_321),
	.B0(\reg_file[3] [1]),
	.B1(n_320),
	.Y(n_322));
   AOI22XL g20923__5477 (.A0(n_412),
	.A1(\reg_file[10] [0]),
	.B0(n_413),
	.B1(\reg_file[11] [0]),
	.Y(n_318));
   AO22XL g20924__2398 (.A0(\reg_file[2] [4]),
	.A1(n_321),
	.B0(\reg_file[3] [4]),
	.B1(n_320),
	.Y(n_317));
   AOI22X1 g20925__5107 (.A0(\reg_file[8] [1]),
	.A1(n_315),
	.B0(\reg_file[9] [1]),
	.B1(n_314),
	.Y(n_316));
   AOI22X1 g20932__6260 (.A0(\reg_file[0] [3]),
	.A1(n_307),
	.B0(\reg_file[1] [3]),
	.B1(n_306),
	.Y(n_313));
   AOI22XL g20928__4319 (.A0(n_412),
	.A1(\reg_file[10] [1]),
	.B0(n_413),
	.B1(\reg_file[11] [1]),
	.Y(n_312));
   AOI22X1 g20929__8428 (.A0(\reg_file[10] [4]),
	.A1(n_412),
	.B0(\reg_file[11] [4]),
	.B1(n_413),
	.Y(n_311));
   NAND2XL g21031__5526 (.A(n_280),
	.B(n_598),
	.Y(n_325));
   CLKINVX1 g20914 (.A(n_310),
	.Y(n_393));
   NOR2XL g20947__6783 (.A(n_266),
	.B(n_267),
	.Y(n_392));
   NAND2XL g20939__3680 (.A(n_262),
	.B(n_258),
	.Y(n_377));
   NAND2XL g20942__1617 (.A(n_257),
	.B(n_255),
	.Y(n_380));
   NAND2XL g21028__2802 (.A(instruction[9]),
	.B(n_598),
	.Y(n_371));
   NAND2XL g20945__1705 (.A(n_264),
	.B(n_263),
	.Y(n_405));
   AND2X1 g20950__5122 (.A(n_259),
	.B(n_261),
	.Y(n_394));
   NOR2XL g20949__8246 (.A(n_269),
	.B(n_256),
	.Y(n_373));
   NAND2XL g20946__7098 (.A(n_268),
	.B(n_260),
	.Y(n_396));
   AOI22X1 g20971__6131 (.A0(\reg_file[0] [2]),
	.A1(n_307),
	.B0(\reg_file[1] [2]),
	.B1(n_306),
	.Y(n_308));
   AOI22X1 g20972__1881 (.A0(\reg_file[8] [0]),
	.A1(n_315),
	.B0(\reg_file[9] [0]),
	.B1(n_314),
	.Y(n_305));
   AOI22X1 g20978__5115 (.A0(\reg_file[8] [5]),
	.A1(n_315),
	.B0(\reg_file[9] [5]),
	.B1(n_314),
	.Y(n_304));
   AOI22X1 g20979__7482 (.A0(\reg_file[2] [2]),
	.A1(n_321),
	.B0(\reg_file[3] [2]),
	.B1(n_320),
	.Y(n_303));
   AOI22X1 g20980__4733 (.A0(\reg_file[0] [1]),
	.A1(n_307),
	.B0(\reg_file[1] [1]),
	.B1(n_306),
	.Y(n_302));
   AOI22X1 g20981__6161 (.A0(\reg_file[8] [7]),
	.A1(n_315),
	.B0(\reg_file[9] [7]),
	.B1(n_314),
	.Y(n_301));
   AOI22X1 g20982__9315 (.A0(\reg_file[0] [5]),
	.A1(n_307),
	.B0(\reg_file[1] [5]),
	.B1(n_306),
	.Y(n_300));
   AOI22X1 g20984__9945 (.A0(\reg_file[0] [6]),
	.A1(n_307),
	.B0(\reg_file[1] [6]),
	.B1(n_306),
	.Y(n_299));
   AO22XL g20985__2883 (.A0(\reg_file[2] [6]),
	.A1(n_321),
	.B0(\reg_file[3] [6]),
	.B1(n_320),
	.Y(n_298));
   AOI22X1 g20989__2346 (.A0(\reg_file[8] [6]),
	.A1(n_315),
	.B0(\reg_file[9] [6]),
	.B1(n_314),
	.Y(n_297));
   AOI22XL g20990__1666 (.A0(n_412),
	.A1(\reg_file[10] [6]),
	.B0(n_413),
	.B1(\reg_file[11] [6]),
	.Y(n_296));
   AOI22X1 g20991__7410 (.A0(\reg_file[8] [2]),
	.A1(n_315),
	.B0(\reg_file[9] [2]),
	.B1(n_314),
	.Y(n_295));
   AO22XL g20995__6417 (.A0(\reg_file[2] [5]),
	.A1(n_321),
	.B0(\reg_file[3] [5]),
	.B1(n_320),
	.Y(n_294));
   AOI22XL g20999__5477 (.A0(n_321),
	.A1(\reg_file[2] [7]),
	.B0(n_320),
	.B1(\reg_file[3] [7]),
	.Y(n_293));
   AOI22X1 g21001__2398 (.A0(\reg_file[0] [7]),
	.A1(n_307),
	.B0(\reg_file[1] [7]),
	.B1(n_306),
	.Y(n_292));
   AOI22X1 g21002__5107 (.A0(\reg_file[0] [0]),
	.A1(n_307),
	.B0(\reg_file[1] [0]),
	.B1(n_306),
	.Y(n_291));
   AOI22X1 g21005__6260 (.A0(\reg_file[8] [3]),
	.A1(n_315),
	.B0(\reg_file[9] [3]),
	.B1(n_314),
	.Y(n_290));
   AOI22X1 g21007__4319 (.A0(\reg_file[2] [3]),
	.A1(n_321),
	.B0(\reg_file[3] [3]),
	.B1(n_320),
	.Y(n_289));
   AOI22X1 g21008__8428 (.A0(\reg_file[0] [4]),
	.A1(n_307),
	.B0(\reg_file[1] [4]),
	.B1(n_306),
	.Y(n_288));
   NAND2XL g21010__5526 (.A(n_252),
	.B(n_254),
	.Y(n_379));
   NOR2XL g21044__3680 (.A(n_236),
	.B(n_240),
	.Y(n_286));
   NOR2XL g21034__1617 (.A(n_228),
	.B(n_230),
	.Y(n_285));
   NOR2XL g21036__2802 (.A(n_239),
	.B(n_242),
	.Y(n_284));
   NOR2XL g21037__1705 (.A(n_231),
	.B(n_227),
	.Y(n_283));
   NOR2XL g21042__5122 (.A(n_225),
	.B(n_222),
	.Y(n_282));
   NOR2XL g21043__8246 (.A(n_226),
	.B(n_237),
	.Y(n_281));
   NOR2XL g21029__7098 (.A(n_280),
	.B(n_279),
	.Y(n_353));
   NOR2XL g21030__6131 (.A(instruction[9]),
	.B(n_279),
	.Y(n_350));
   NOR2XL g21019__1881 (.A(n_273),
	.B(n_270),
	.Y(n_278));
   NOR2XL g21048__5115 (.A(n_221),
	.B(n_220),
	.Y(n_277));
   NOR2XL g21049__7482 (.A(n_219),
	.B(n_218),
	.Y(n_276));
   NOR2XL g21018__6161 (.A(n_272),
	.B(n_271),
	.Y(n_274));
   NOR2XL g21014__9315 (.A(n_273),
	.B(n_272),
	.Y(n_336));
   NOR2XL g21015__9945 (.A(n_271),
	.B(n_270),
	.Y(n_335));
   NOR2XL g20937__2883 (.A(n_217),
	.B(n_241),
	.Y(n_310));
   NOR2XL g20948__2346 (.A(n_235),
	.B(n_238),
	.Y(n_372));
   NAND4XL g21021__1666 (.A(n_172),
	.B(n_168),
	.C(n_169),
	.D(n_144),
	.Y(n_269));
   NOR2XL g21024__7410 (.A(n_210),
	.B(n_202),
	.Y(n_268));
   NAND4XL g21025__6417 (.A(n_122),
	.B(n_156),
	.C(n_167),
	.D(n_193),
	.Y(n_267));
   NAND4XL g21026__5477 (.A(n_139),
	.B(n_162),
	.C(n_165),
	.D(n_183),
	.Y(n_266));
   NOR2XL g21027__2398 (.A(n_251),
	.B(n_253),
	.Y(n_265));
   NOR2XL g21032__5107 (.A(n_197),
	.B(n_215),
	.Y(n_264));
   NOR2XL g21035__6260 (.A(n_214),
	.B(n_213),
	.Y(n_263));
   NOR2XL g21038__4319 (.A(n_207),
	.B(n_205),
	.Y(n_262));
   NOR2XL g21039__8428 (.A(n_209),
	.B(n_211),
	.Y(n_261));
   NOR2XL g21040__5526 (.A(n_212),
	.B(n_208),
	.Y(n_260));
   NOR2XL g21041__6783 (.A(n_216),
	.B(n_206),
	.Y(n_259));
   NOR2XL g21045__3680 (.A(n_203),
	.B(n_204),
	.Y(n_258));
   NOR2XL g21050__1617 (.A(n_199),
	.B(n_198),
	.Y(n_257));
   NAND4XL g21020__2802 (.A(n_136),
	.B(n_173),
	.C(n_176),
	.D(n_180),
	.Y(n_256));
   NOR2XL g21051__1705 (.A(n_201),
	.B(n_200),
	.Y(n_255));
   NOR2XL g21017__5122 (.A(n_253),
	.B(n_248),
	.Y(n_254));
   NOR2XL g21016__8246 (.A(n_249),
	.B(n_251),
	.Y(n_252));
   NOR2XL g21013__7098 (.A(n_249),
	.B(n_248),
	.Y(n_250));
   NOR2XL g21075__1881 (.A(n_247),
	.B(n_244),
	.Y(n_356));
   NOR2XL g21082__5115 (.A(n_246),
	.B(n_245),
	.Y(n_363));
   NOR2XL g21077__7482 (.A(n_370),
	.B(n_245),
	.Y(n_362));
   NOR2XL g21076__4733 (.A(n_246),
	.B(n_244),
	.Y(n_366));
   NOR2XL g21081__6161 (.A(n_243),
	.B(n_245),
	.Y(n_385));
   NOR2XL g21074__9315 (.A(n_243),
	.B(n_244),
	.Y(n_357));
   NOR2XL g21079__9945 (.A(n_370),
	.B(n_244),
	.Y(n_365));
   NOR2XL g21080__2883 (.A(n_247),
	.B(n_245),
	.Y(n_384));
   NAND2XL g21059__2346 (.A(n_133),
	.B(n_161),
	.Y(n_242));
   NAND4XL g21033__1666 (.A(n_71),
	.B(n_73),
	.C(n_72),
	.D(n_40),
	.Y(n_241));
   NAND2XL g21053__7410 (.A(n_138),
	.B(n_113),
	.Y(n_240));
   NAND2XL g21058__6417 (.A(n_154),
	.B(n_140),
	.Y(n_239));
   NAND4XL g21023__5477 (.A(n_47),
	.B(n_90),
	.C(n_87),
	.D(n_85),
	.Y(n_238));
   NAND2XL g21060__2398 (.A(n_179),
	.B(n_155),
	.Y(n_237));
   NAND2XL g21061__5107 (.A(n_191),
	.B(n_192),
	.Y(n_236));
   NAND4XL g21022__6260 (.A(n_95),
	.B(n_100),
	.C(n_98),
	.D(n_99),
	.Y(n_235));
   NAND2XL g21062__4319 (.A(instruction[10]),
	.B(n_195),
	.Y(n_279));
   NAND2XL g21068__8428 (.A(n_185),
	.B(n_186),
	.Y(n_270));
   NOR2XL g21078__5526 (.A(n_370),
	.B(n_234),
	.Y(n_314));
   NOR2XL g21071__6783 (.A(n_247),
	.B(n_234),
	.Y(n_306));
   NOR2XL g21072__3680 (.A(n_243),
	.B(n_233),
	.Y(n_321));
   NOR2XL g21073__1617 (.A(n_247),
	.B(n_233),
	.Y(n_320));
   NOR2XL g21070__2802 (.A(n_246),
	.B(n_233),
	.Y(n_412));
   NOR2XL g21083__1705 (.A(n_246),
	.B(n_234),
	.Y(n_315));
   NOR2XL g21084__5122 (.A(n_370),
	.B(n_233),
	.Y(n_413));
   NOR2XL g21069__8246 (.A(n_243),
	.B(n_234),
	.Y(n_307));
   AND2X1 g21104__7098 (.A(n_123),
	.B(n_148),
	.Y(n_232));
   NAND2XL g21087__6131 (.A(n_130),
	.B(n_143),
	.Y(n_231));
   NAND2XL g21088__1881 (.A(n_157),
	.B(n_135),
	.Y(n_230));
   NAND2XL g21090__7482 (.A(n_152),
	.B(n_153),
	.Y(n_228));
   NAND2XL g21095__4733 (.A(n_132),
	.B(n_129),
	.Y(n_227));
   NAND2XL g21096__6161 (.A(n_137),
	.B(n_141),
	.Y(n_226));
   NAND2XL g21101__9315 (.A(n_134),
	.B(n_149),
	.Y(n_225));
   AND2X1 g21103__9945 (.A(n_126),
	.B(n_145),
	.Y(n_224));
   NAND2XL g21107__2346 (.A(n_147),
	.B(n_131),
	.Y(n_222));
   NAND2XL g21108__1666 (.A(n_160),
	.B(n_120),
	.Y(n_221));
   NAND2XL g21109__7410 (.A(n_118),
	.B(n_119),
	.Y(n_220));
   NAND2XL g21111__6417 (.A(n_117),
	.B(n_142),
	.Y(n_219));
   NAND2XL g21112__5477 (.A(n_115),
	.B(n_116),
	.Y(n_218));
   NAND4XL g21012__2398 (.A(n_64),
	.B(n_109),
	.C(n_75),
	.D(n_76),
	.Y(n_217));
   NAND2XL g21117__5107 (.A(n_121),
	.B(n_187),
	.Y(n_272));
   NAND2XL g21116__6260 (.A(n_125),
	.B(n_114),
	.Y(n_271));
   NAND2XL g21115__4319 (.A(n_184),
	.B(n_190),
	.Y(n_273));
   NAND2XL g21094__8428 (.A(n_51),
	.B(n_84),
	.Y(n_216));
   NAND2XL g21054__5526 (.A(n_68),
	.B(n_105),
	.Y(n_215));
   NAND2XL g21055__6783 (.A(n_67),
	.B(n_66),
	.Y(n_214));
   NAND2XL g21056__3680 (.A(n_69),
	.B(n_65),
	.Y(n_213));
   NAND2XL g21057__1617 (.A(n_59),
	.B(n_38),
	.Y(n_212));
   NAND2XL g21052__2802 (.A(n_58),
	.B(n_106),
	.Y(n_211));
   NAND2XL g21093__1705 (.A(n_56),
	.B(n_54),
	.Y(n_210));
   NAND2XL g21092__5122 (.A(n_77),
	.B(n_39),
	.Y(n_209));
   NAND2XL g21091__8246 (.A(n_50),
	.B(n_60),
	.Y(n_208));
   NAND2XL g21086__7098 (.A(n_49),
	.B(n_48),
	.Y(n_207));
   NAND2XL g21064__6131 (.A(n_103),
	.B(n_92),
	.Y(n_253));
   NAND2XL g21065__1881 (.A(n_112),
	.B(n_83),
	.Y(n_249));
   NAND2XL g21067__5115 (.A(n_79),
	.B(n_80),
	.Y(n_248));
   NAND2XL g21063__7482 (.A(n_104),
	.B(n_52),
	.Y(n_251));
   DFFRHQX1 mem_write_reg (.CK(clk),
	.D(FE_PHN6_n_62),
	.Q(mem_write),
	.RN(n_584));
   NAND2XL g21098__4733 (.A(n_111),
	.B(n_55),
	.Y(n_206));
   NAND2XL g21099__6161 (.A(n_46),
	.B(n_63),
	.Y(n_205));
   NAND2XL g21100__9315 (.A(n_42),
	.B(n_43),
	.Y(n_204));
   NAND2XL g21102__9945 (.A(n_45),
	.B(n_44),
	.Y(n_203));
   NAND2XL g21105__2883 (.A(n_61),
	.B(n_57),
	.Y(n_202));
   NAND2XL g21106__2346 (.A(n_110),
	.B(n_33),
	.Y(n_201));
   NAND2XL g21110__1666 (.A(n_41),
	.B(n_32),
	.Y(n_200));
   NAND2XL g21113__7410 (.A(n_37),
	.B(n_36),
	.Y(n_199));
   NAND2XL g21114__6417 (.A(n_34),
	.B(n_35),
	.Y(n_198));
   NAND2XL g21097__5477 (.A(n_74),
	.B(n_53),
	.Y(n_197));
   NAND2XL g21185__2398 (.A(instruction[9]),
	.B(n_194),
	.Y(n_245));
   NAND2XL g21184__5107 (.A(n_280),
	.B(n_194),
	.Y(n_244));
   AOI22X1 g21160__6260 (.A0(n_189),
	.A1(\reg_file[12] [7]),
	.B0(n_188),
	.B1(\reg_file[13] [7]),
	.Y(n_193));
   DFFRHQX1 \addr_reg[2]  (.CK(clk),
	.D(n_30),
	.Q(addr[2]),
	.RN(n_584));
   DFFRHQX1 \addr_reg[3]  (.CK(clk),
	.D(n_26),
	.Q(addr[3]),
	.RN(n_584));
   AOI22X1 g21125__4319 (.A0(n_182),
	.A1(\reg_file[4] [1]),
	.B0(n_181),
	.B1(\reg_file[5] [1]),
	.Y(n_192));
   AOI22X1 g21127__8428 (.A0(n_171),
	.A1(\reg_file[6] [1]),
	.B0(n_170),
	.B1(\reg_file[7] [1]),
	.Y(n_191));
   AOI22X1 g21128__5526 (.A0(n_189),
	.A1(\reg_file[12] [0]),
	.B0(n_188),
	.B1(\reg_file[13] [0]),
	.Y(n_190));
   AOI22X1 g21130__6783 (.A0(n_175),
	.A1(\reg_file[10] [0]),
	.B0(n_174),
	.B1(\reg_file[11] [0]),
	.Y(n_187));
   AOI22X1 g21131__3680 (.A0(n_164),
	.A1(\reg_file[2] [0]),
	.B0(n_163),
	.B1(\reg_file[3] [0]),
	.Y(n_186));
   AOI22X1 g21133__1617 (.A0(n_178),
	.A1(\reg_file[0] [0]),
	.B0(n_177),
	.B1(\reg_file[1] [0]),
	.Y(n_185));
   AOI22X1 g21135__2802 (.A0(n_159),
	.A1(\reg_file[14] [0]),
	.B0(n_158),
	.B1(\reg_file[15] [0]),
	.Y(n_184));
   AOI22X1 g21137__1705 (.A0(n_182),
	.A1(\reg_file[4] [7]),
	.B0(n_181),
	.B1(\reg_file[5] [7]),
	.Y(n_183));
   AOI22X1 g21138__5122 (.A0(n_189),
	.A1(\reg_file[12] [6]),
	.B0(n_188),
	.B1(\reg_file[13] [6]),
	.Y(n_180));
   AOI22X1 g21139__8246 (.A0(n_178),
	.A1(\reg_file[0] [2]),
	.B0(n_177),
	.B1(\reg_file[1] [2]),
	.Y(n_179));
   AOI22X1 g21140__7098 (.A0(n_175),
	.A1(\reg_file[10] [6]),
	.B0(n_174),
	.B1(\reg_file[11] [6]),
	.Y(n_176));
   AOI22X1 g21141__6131 (.A0(n_151),
	.A1(\reg_file[8] [6]),
	.B0(n_150),
	.B1(\reg_file[9] [6]),
	.Y(n_173));
   AOI22X1 g21143__1881 (.A0(n_171),
	.A1(\reg_file[6] [6]),
	.B0(n_170),
	.B1(\reg_file[7] [6]),
	.Y(n_172));
   AOI22X1 g21144__5115 (.A0(n_182),
	.A1(\reg_file[4] [6]),
	.B0(n_181),
	.B1(\reg_file[5] [6]),
	.Y(n_169));
   AOI22X1 g21145__7482 (.A0(n_178),
	.A1(\reg_file[0] [6]),
	.B0(n_177),
	.B1(\reg_file[1] [6]),
	.Y(n_168));
   DFFRHQX1 mem_read_reg (.CK(clk),
	.D(n_27),
	.Q(mem_read),
	.RN(n_584));
   AOI22X1 g21161__4733 (.A0(n_175),
	.A1(\reg_file[10] [7]),
	.B0(n_174),
	.B1(\reg_file[11] [7]),
	.Y(n_167));
   AOI22X1 g21162__6161 (.A0(n_189),
	.A1(\reg_file[12] [4]),
	.B0(n_188),
	.B1(\reg_file[13] [4]),
	.Y(n_166));
   AOI22X1 g21163__9315 (.A0(n_164),
	.A1(\reg_file[2] [7]),
	.B0(n_163),
	.B1(\reg_file[3] [7]),
	.Y(n_165));
   AOI22X1 g21164__9945 (.A0(n_178),
	.A1(\reg_file[0] [7]),
	.B0(n_177),
	.B1(\reg_file[1] [7]),
	.Y(n_162));
   AOI22X1 g21165__2883 (.A0(n_175),
	.A1(\reg_file[10] [1]),
	.B0(n_174),
	.B1(\reg_file[11] [1]),
	.Y(n_161));
   AOI22X1 g21174__2346 (.A0(n_159),
	.A1(\reg_file[14] [5]),
	.B0(n_158),
	.B1(\reg_file[15] [5]),
	.Y(n_160));
   AOI22X1 g21177__1666 (.A0(n_171),
	.A1(\reg_file[6] [2]),
	.B0(n_170),
	.B1(\reg_file[7] [2]),
	.Y(n_157));
   AOI22X1 g21179__7410 (.A0(n_159),
	.A1(\reg_file[14] [7]),
	.B0(n_158),
	.B1(\reg_file[15] [7]),
	.Y(n_156));
   AOI22X1 g21180__6417 (.A0(n_164),
	.A1(\reg_file[2] [2]),
	.B0(n_163),
	.B1(\reg_file[3] [2]),
	.Y(n_155));
   AOI22X1 g21181__5477 (.A0(n_159),
	.A1(\reg_file[14] [1]),
	.B0(n_158),
	.B1(\reg_file[15] [1]),
	.Y(n_154));
   AOI22X1 g21182__2398 (.A0(n_175),
	.A1(\reg_file[10] [2]),
	.B0(n_174),
	.B1(\reg_file[11] [2]),
	.Y(n_153));
   AOI22X1 g21193__5107 (.A0(n_151),
	.A1(\reg_file[8] [2]),
	.B0(n_150),
	.B1(\reg_file[9] [2]),
	.Y(n_152));
   AOI22X1 g21191__6260 (.A0(n_175),
	.A1(\reg_file[10] [3]),
	.B0(n_174),
	.B1(\reg_file[11] [3]),
	.Y(n_149));
   AOI22X1 g21188__4319 (.A0(n_164),
	.A1(\reg_file[2] [4]),
	.B0(n_163),
	.B1(\reg_file[3] [4]),
	.Y(n_148));
   AOI22X1 g21189__8428 (.A0(n_171),
	.A1(\reg_file[6] [3]),
	.B0(n_170),
	.B1(\reg_file[7] [3]),
	.Y(n_147));
   NAND2XL g21186__5526 (.A(n_280),
	.B(n_146),
	.Y(n_234));
   NAND2XL g21183__6783 (.A(instruction[9]),
	.B(n_146),
	.Y(n_233));
   AOI22X1 g21231__3680 (.A0(n_175),
	.A1(\reg_file[10] [4]),
	.B0(n_174),
	.B1(\reg_file[11] [4]),
	.Y(n_145));
   AOI22X1 g21196__1617 (.A0(n_164),
	.A1(\reg_file[2] [6]),
	.B0(n_163),
	.B1(\reg_file[3] [6]),
	.Y(n_144));
   AOI22X1 g21198__2802 (.A0(n_189),
	.A1(\reg_file[12] [3]),
	.B0(n_188),
	.B1(\reg_file[13] [3]),
	.Y(n_143));
   AOI22X1 g21246__1705 (.A0(n_182),
	.A1(\reg_file[4] [5]),
	.B0(n_181),
	.B1(\reg_file[5] [5]),
	.Y(n_142));
   AOI22X1 g21201__5122 (.A0(n_189),
	.A1(\reg_file[12] [2]),
	.B0(n_188),
	.B1(\reg_file[13] [2]),
	.Y(n_141));
   AOI22X1 g21203__8246 (.A0(n_189),
	.A1(\reg_file[12] [1]),
	.B0(n_188),
	.B1(\reg_file[13] [1]),
	.Y(n_140));
   AOI22X1 g21205__7098 (.A0(n_171),
	.A1(\reg_file[6] [7]),
	.B0(n_170),
	.B1(\reg_file[7] [7]),
	.Y(n_139));
   AOI22X1 g21206__6131 (.A0(n_178),
	.A1(\reg_file[0] [1]),
	.B0(n_177),
	.B1(\reg_file[1] [1]),
	.Y(n_138));
   AOI22X1 g21207__1881 (.A0(n_159),
	.A1(\reg_file[14] [2]),
	.B0(n_158),
	.B1(\reg_file[15] [2]),
	.Y(n_137));
   AOI22X1 g21210__5115 (.A0(n_159),
	.A1(\reg_file[14] [6]),
	.B0(n_158),
	.B1(\reg_file[15] [6]),
	.Y(n_136));
   AOI22X1 g21213__7482 (.A0(n_182),
	.A1(\reg_file[4] [2]),
	.B0(n_181),
	.B1(\reg_file[5] [2]),
	.Y(n_135));
   AOI22X1 g21214__4733 (.A0(n_151),
	.A1(\reg_file[8] [3]),
	.B0(n_150),
	.B1(\reg_file[9] [3]),
	.Y(n_134));
   AOI22X1 g21216__6161 (.A0(n_151),
	.A1(\reg_file[8] [1]),
	.B0(n_150),
	.B1(\reg_file[9] [1]),
	.Y(n_133));
   AOI22X1 g21217__9315 (.A0(n_178),
	.A1(\reg_file[0] [3]),
	.B0(n_177),
	.B1(\reg_file[1] [3]),
	.Y(n_132));
   AOI22X1 g21219__9945 (.A0(n_182),
	.A1(\reg_file[4] [3]),
	.B0(n_181),
	.B1(\reg_file[5] [3]),
	.Y(n_131));
   AOI22X1 g21220__2883 (.A0(n_159),
	.A1(\reg_file[14] [3]),
	.B0(n_158),
	.B1(\reg_file[15] [3]),
	.Y(n_130));
   AOI22X1 g21221__2346 (.A0(n_164),
	.A1(\reg_file[2] [3]),
	.B0(n_163),
	.B1(\reg_file[3] [3]),
	.Y(n_129));
   AOI22X1 g21230__1666 (.A0(n_159),
	.A1(\reg_file[14] [4]),
	.B0(n_158),
	.B1(\reg_file[15] [4]),
	.Y(n_128));
   AOI22X1 g21194__7410 (.A0(n_171),
	.A1(\reg_file[6] [4]),
	.B0(n_170),
	.B1(\reg_file[7] [4]),
	.Y(n_127));
   AOI22X1 g21232__6417 (.A0(n_151),
	.A1(\reg_file[8] [4]),
	.B0(n_150),
	.B1(\reg_file[9] [4]),
	.Y(n_126));
   AOI22X1 g21233__5477 (.A0(n_171),
	.A1(\reg_file[6] [0]),
	.B0(n_170),
	.B1(\reg_file[7] [0]),
	.Y(n_125));
   AOI22X1 g21234__2398 (.A0(n_182),
	.A1(\reg_file[4] [4]),
	.B0(n_181),
	.B1(\reg_file[5] [4]),
	.Y(n_124));
   AOI22X1 g21235__5107 (.A0(n_178),
	.A1(\reg_file[0] [4]),
	.B0(n_177),
	.B1(\reg_file[1] [4]),
	.Y(n_123));
   AOI22X1 g21237__6260 (.A0(n_151),
	.A1(\reg_file[8] [7]),
	.B0(n_150),
	.B1(\reg_file[9] [7]),
	.Y(n_122));
   AOI22X1 g21241__4319 (.A0(n_151),
	.A1(\reg_file[8] [0]),
	.B0(n_150),
	.B1(\reg_file[9] [0]),
	.Y(n_121));
   AOI22X1 g21242__8428 (.A0(n_189),
	.A1(\reg_file[12] [5]),
	.B0(n_188),
	.B1(\reg_file[13] [5]),
	.Y(n_120));
   AOI22X1 g21243__5526 (.A0(n_175),
	.A1(\reg_file[10] [5]),
	.B0(n_174),
	.B1(\reg_file[11] [5]),
	.Y(n_119));
   AOI22X1 g21244__6783 (.A0(n_151),
	.A1(\reg_file[8] [5]),
	.B0(n_150),
	.B1(\reg_file[9] [5]),
	.Y(n_118));
   AOI22X1 g21245__3680 (.A0(n_171),
	.A1(\reg_file[6] [5]),
	.B0(n_170),
	.B1(\reg_file[7] [5]),
	.Y(n_117));
   AOI22X1 g21247__1617 (.A0(n_164),
	.A1(\reg_file[2] [5]),
	.B0(n_163),
	.B1(\reg_file[3] [5]),
	.Y(n_116));
   AOI22X1 g21248__2802 (.A0(n_178),
	.A1(\reg_file[0] [5]),
	.B0(n_177),
	.B1(\reg_file[1] [5]),
	.Y(n_115));
   AOI22X1 g21249__1705 (.A0(n_182),
	.A1(\reg_file[4] [0]),
	.B0(n_181),
	.B1(\reg_file[5] [0]),
	.Y(n_114));
   AOI22X1 g21256__5122 (.A0(n_164),
	.A1(\reg_file[2] [1]),
	.B0(n_163),
	.B1(\reg_file[3] [1]),
	.Y(n_113));
   DFFRHQX1 \addr_reg[1]  (.CK(clk),
	.D(n_25),
	.Q(addr[1]),
	.RN(n_584));
   DFFRHQX1 \addr_reg[0]  (.CK(clk),
	.D(n_29),
	.Q(addr[0]),
	.RN(n_584));
   OAI22XL g21257__8246 (.A0(n_31),
	.A1(instruction[14]),
	.B0(n_480),
	.B1(instruction[13]),
	.Y(n_195));
   AOI22X1 g21155__7098 (.A0(n_108),
	.A1(\reg_file[14] [0]),
	.B0(n_107),
	.B1(\reg_file[15] [0]),
	.Y(n_112));
   AOI22X1 g21126__6131 (.A0(n_91),
	.A1(\reg_file[5] [3]),
	.B0(n_101),
	.B1(\reg_file[7] [3]),
	.Y(n_111));
   AOI22X1 g21129__1881 (.A0(n_78),
	.A1(\reg_file[0] [5]),
	.B0(n_102),
	.B1(\reg_file[6] [5]),
	.Y(n_110));
   AOI22X1 g21132__5115 (.A0(n_108),
	.A1(\reg_file[14] [7]),
	.B0(n_107),
	.B1(\reg_file[15] [7]),
	.Y(n_109));
   AOI22X1 g21134__7482 (.A0(n_89),
	.A1(\reg_file[2] [3]),
	.B0(n_88),
	.B1(\reg_file[3] [3]),
	.Y(n_106));
   AOI22X1 g21136__4733 (.A0(n_97),
	.A1(\reg_file[10] [1]),
	.B0(n_96),
	.B1(\reg_file[11] [1]),
	.Y(n_105));
   AOI22X1 g21142__6161 (.A0(n_94),
	.A1(\reg_file[8] [0]),
	.B0(n_93),
	.B1(\reg_file[9] [0]),
	.Y(n_104));
   AOI22X1 g21146__9315 (.A0(n_102),
	.A1(\reg_file[6] [0]),
	.B0(n_101),
	.B1(\reg_file[7] [0]),
	.Y(n_103));
   AOI22X1 g21147__9945 (.A0(n_108),
	.A1(\reg_file[14] [6]),
	.B0(n_107),
	.B1(\reg_file[15] [6]),
	.Y(n_100));
   AOI22X1 g21148__2883 (.A0(n_82),
	.A1(\reg_file[12] [6]),
	.B0(n_81),
	.B1(\reg_file[13] [6]),
	.Y(n_99));
   AOI22X1 g21149__2346 (.A0(n_97),
	.A1(\reg_file[10] [6]),
	.B0(n_96),
	.B1(\reg_file[11] [6]),
	.Y(n_98));
   AOI22X1 g21150__1666 (.A0(n_94),
	.A1(\reg_file[8] [6]),
	.B0(n_93),
	.B1(\reg_file[9] [6]),
	.Y(n_95));
   AOI22X1 g21151__7410 (.A0(n_86),
	.A1(\reg_file[4] [0]),
	.B0(n_91),
	.B1(\reg_file[5] [0]),
	.Y(n_92));
   AOI22X1 g21152__6417 (.A0(n_89),
	.A1(\reg_file[2] [6]),
	.B0(n_88),
	.B1(\reg_file[3] [6]),
	.Y(n_90));
   AOI22X1 g21153__5477 (.A0(n_86),
	.A1(\reg_file[4] [6]),
	.B0(n_102),
	.B1(\reg_file[6] [6]),
	.Y(n_87));
   AOI22X1 g21154__2398 (.A0(n_91),
	.A1(\reg_file[5] [6]),
	.B0(n_101),
	.B1(\reg_file[7] [6]),
	.Y(n_85));
   AOI22X1 g21124__5107 (.A0(n_108),
	.A1(\reg_file[14] [3]),
	.B0(n_107),
	.B1(\reg_file[15] [3]),
	.Y(n_84));
   AOI22X1 g21156__6260 (.A0(n_82),
	.A1(\reg_file[12] [0]),
	.B0(n_81),
	.B1(\reg_file[13] [0]),
	.Y(n_83));
   AOI22X1 g21157__4319 (.A0(n_89),
	.A1(\reg_file[2] [0]),
	.B0(n_88),
	.B1(\reg_file[3] [0]),
	.Y(n_80));
   AOI22X1 g21158__8428 (.A0(n_78),
	.A1(\reg_file[0] [0]),
	.B0(n_70),
	.B1(\reg_file[1] [0]),
	.Y(n_79));
   AOI22X1 g21159__5526 (.A0(n_94),
	.A1(\reg_file[8] [3]),
	.B0(n_93),
	.B1(\reg_file[9] [3]),
	.Y(n_77));
   AOI22X1 g21166__6783 (.A0(n_97),
	.A1(\reg_file[10] [7]),
	.B0(n_96),
	.B1(\reg_file[11] [7]),
	.Y(n_76));
   AOI22X1 g21167__3680 (.A0(n_82),
	.A1(\reg_file[12] [7]),
	.B0(n_81),
	.B1(\reg_file[13] [7]),
	.Y(n_75));
   AOI22X1 g21168__1617 (.A0(n_108),
	.A1(\reg_file[14] [1]),
	.B0(n_107),
	.B1(\reg_file[15] [1]),
	.Y(n_74));
   AOI22X1 g21169__2802 (.A0(n_86),
	.A1(\reg_file[4] [7]),
	.B0(n_102),
	.B1(\reg_file[6] [7]),
	.Y(n_73));
   AOI22X1 g21170__1705 (.A0(n_89),
	.A1(\reg_file[2] [7]),
	.B0(n_88),
	.B1(\reg_file[3] [7]),
	.Y(n_72));
   AOI22X1 g21171__5122 (.A0(n_78),
	.A1(\reg_file[0] [7]),
	.B0(n_70),
	.B1(\reg_file[1] [7]),
	.Y(n_71));
   AOI22X1 g21172__8246 (.A0(n_78),
	.A1(\reg_file[0] [1]),
	.B0(n_70),
	.B1(\reg_file[1] [1]),
	.Y(n_69));
   AOI22X1 g21173__7098 (.A0(n_94),
	.A1(\reg_file[8] [1]),
	.B0(n_93),
	.B1(\reg_file[9] [1]),
	.Y(n_68));
   AOI22X1 g21175__6131 (.A0(n_102),
	.A1(\reg_file[6] [1]),
	.B0(n_101),
	.B1(\reg_file[7] [1]),
	.Y(n_67));
   AOI22X1 g21176__1881 (.A0(n_86),
	.A1(\reg_file[4] [1]),
	.B0(n_91),
	.B1(\reg_file[5] [1]),
	.Y(n_66));
   AOI22X1 g21178__5115 (.A0(n_89),
	.A1(\reg_file[2] [1]),
	.B0(n_88),
	.B1(\reg_file[3] [1]),
	.Y(n_65));
   AOI22X1 g21190__7482 (.A0(n_94),
	.A1(\reg_file[8] [7]),
	.B0(n_93),
	.B1(\reg_file[9] [7]),
	.Y(n_64));
   AOI22X1 g21224__4733 (.A0(n_97),
	.A1(\reg_file[10] [4]),
	.B0(n_96),
	.B1(\reg_file[11] [4]),
	.Y(n_63));
   NOR3XL g21265__6161 (.A(instruction[14]),
	.B(instruction[15]),
	.C(n_374),
	.Y(n_62));
   AOI22X1 g21195__9315 (.A0(n_86),
	.A1(\reg_file[4] [2]),
	.B0(n_102),
	.B1(\reg_file[6] [2]),
	.Y(n_61));
   AOI22X1 g21197__9945 (.A0(n_82),
	.A1(\reg_file[12] [2]),
	.B0(n_81),
	.B1(\reg_file[13] [2]),
	.Y(n_60));
   AOI22X1 g21199__2883 (.A0(n_78),
	.A1(\reg_file[0] [2]),
	.B0(n_70),
	.B1(\reg_file[1] [2]),
	.Y(n_59));
   AOI22X1 g21200__2346 (.A0(n_78),
	.A1(\reg_file[0] [3]),
	.B0(n_70),
	.B1(\reg_file[1] [3]),
	.Y(n_58));
   AOI22X1 g21202__1666 (.A0(n_91),
	.A1(\reg_file[5] [2]),
	.B0(n_101),
	.B1(\reg_file[7] [2]),
	.Y(n_57));
   AOI22X1 g21204__7410 (.A0(n_94),
	.A1(\reg_file[8] [2]),
	.B0(n_93),
	.B1(\reg_file[9] [2]),
	.Y(n_56));
   AOI22X1 g21208__6417 (.A0(n_82),
	.A1(\reg_file[12] [3]),
	.B0(n_81),
	.B1(\reg_file[13] [3]),
	.Y(n_55));
   AOI22X1 g21209__5477 (.A0(n_97),
	.A1(\reg_file[10] [2]),
	.B0(n_96),
	.B1(\reg_file[11] [2]),
	.Y(n_54));
   AOI22X1 g21211__2398 (.A0(n_82),
	.A1(\reg_file[12] [1]),
	.B0(n_81),
	.B1(\reg_file[13] [1]),
	.Y(n_53));
   AOI22X1 g21212__5107 (.A0(n_97),
	.A1(\reg_file[10] [0]),
	.B0(n_96),
	.B1(\reg_file[11] [0]),
	.Y(n_52));
   AOI22X1 g21215__6260 (.A0(n_86),
	.A1(\reg_file[4] [3]),
	.B0(n_102),
	.B1(\reg_file[6] [3]),
	.Y(n_51));
   AOI22X1 g21218__4319 (.A0(n_89),
	.A1(\reg_file[2] [2]),
	.B0(n_88),
	.B1(\reg_file[3] [2]),
	.Y(n_50));
   AOI22X1 g21222__8428 (.A0(n_108),
	.A1(\reg_file[14] [4]),
	.B0(n_107),
	.B1(\reg_file[15] [4]),
	.Y(n_49));
   AOI22X1 g21223__5526 (.A0(n_82),
	.A1(\reg_file[12] [4]),
	.B0(n_81),
	.B1(\reg_file[13] [4]),
	.Y(n_48));
   AOI22X1 g21192__6783 (.A0(n_78),
	.A1(\reg_file[0] [6]),
	.B0(n_70),
	.B1(\reg_file[1] [6]),
	.Y(n_47));
   AOI22X1 g21225__3680 (.A0(n_94),
	.A1(\reg_file[8] [4]),
	.B0(n_93),
	.B1(\reg_file[9] [4]),
	.Y(n_46));
   AOI22X1 g21226__1617 (.A0(n_102),
	.A1(\reg_file[6] [4]),
	.B0(n_101),
	.B1(\reg_file[7] [4]),
	.Y(n_45));
   AOI22X1 g21227__2802 (.A0(n_86),
	.A1(\reg_file[4] [4]),
	.B0(n_91),
	.B1(\reg_file[5] [4]),
	.Y(n_44));
   AOI22X1 g21228__1705 (.A0(n_70),
	.A1(\reg_file[1] [4]),
	.B0(n_88),
	.B1(\reg_file[3] [4]),
	.Y(n_43));
   AOI22X1 g21229__5122 (.A0(n_78),
	.A1(\reg_file[0] [4]),
	.B0(n_89),
	.B1(\reg_file[2] [4]),
	.Y(n_42));
   AOI22X1 g21236__8246 (.A0(n_89),
	.A1(\reg_file[2] [5]),
	.B0(n_88),
	.B1(\reg_file[3] [5]),
	.Y(n_41));
   AOI22X1 g21238__7098 (.A0(n_91),
	.A1(\reg_file[5] [7]),
	.B0(n_101),
	.B1(\reg_file[7] [7]),
	.Y(n_40));
   AOI22X1 g21239__6131 (.A0(n_97),
	.A1(\reg_file[10] [3]),
	.B0(n_96),
	.B1(\reg_file[11] [3]),
	.Y(n_39));
   AOI22X1 g21240__1881 (.A0(n_108),
	.A1(\reg_file[14] [2]),
	.B0(n_107),
	.B1(\reg_file[15] [2]),
	.Y(n_38));
   AOI22X1 g21250__5115 (.A0(n_108),
	.A1(\reg_file[14] [5]),
	.B0(n_107),
	.B1(\reg_file[15] [5]),
	.Y(n_37));
   AOI22X1 g21251__7482 (.A0(n_82),
	.A1(\reg_file[12] [5]),
	.B0(n_81),
	.B1(\reg_file[13] [5]),
	.Y(n_36));
   AOI22X1 g21252__4733 (.A0(n_97),
	.A1(\reg_file[10] [5]),
	.B0(n_96),
	.B1(\reg_file[11] [5]),
	.Y(n_35));
   AOI22X1 g21253__6161 (.A0(n_94),
	.A1(\reg_file[8] [5]),
	.B0(n_93),
	.B1(\reg_file[9] [5]),
	.Y(n_34));
   AOI22X1 g21255__9315 (.A0(n_70),
	.A1(\reg_file[1] [5]),
	.B0(n_101),
	.B1(\reg_file[7] [5]),
	.Y(n_33));
   AOI22X1 g21254__9945 (.A0(n_86),
	.A1(\reg_file[4] [5]),
	.B0(n_91),
	.B1(\reg_file[5] [5]),
	.Y(n_32));
   AND2X1 g21261__2883 (.A(instruction[10]),
	.B(n_31),
	.Y(n_194));
   NOR2XL g21264__2346 (.A(n_4),
	.B(n_28),
	.Y(n_30));
   NOR2XL g21263__1666 (.A(n_3),
	.B(n_28),
	.Y(n_29));
   NOR2XL g21262__7410 (.A(FE_PHN5_instruction_12),
	.B(n_28),
	.Y(n_27));
   NOR2XL g21258__6417 (.A(n_5),
	.B(n_28),
	.Y(n_26));
   NOR2XL g21259__5477 (.A(n_6),
	.B(n_28),
	.Y(n_25));
   NOR2XL g21260__2398 (.A(instruction[10]),
	.B(n_24),
	.Y(n_146));
   INVXL g21266 (.A(n_24),
	.Y(n_31));
   INVXL g21286 (.A(n_370),
	.Y(n_351));
   NOR2XL g21270__5107 (.A(n_23),
	.B(n_20),
	.Y(n_188));
   NOR2XL g21273__6260 (.A(n_23),
	.B(n_17),
	.Y(n_174));
   NOR2BXL g21269__4319 (.AN(n_21),
	.B(n_22),
	.Y(n_177));
   NOR2XL g21271__8428 (.A(n_18),
	.B(n_22),
	.Y(n_170));
   NOR2BXL g21278__5526 (.AN(n_21),
	.B(n_19),
	.Y(n_151));
   NOR2XL g21302__6783 (.A(n_20),
	.B(n_19),
	.Y(n_189));
   NOR2XL g21279__3680 (.A(n_18),
	.B(n_19),
	.Y(n_159));
   NOR2BXL g21292__1617 (.AN(n_16),
	.B(n_17),
	.Y(n_164));
   NOR2XL g21304__2802 (.A(n_17),
	.B(n_19),
	.Y(n_175));
   NOR2XL g21296__1705 (.A(n_22),
	.B(n_20),
	.Y(n_181));
   NOR2XL g21297__5122 (.A(n_22),
	.B(n_17),
	.Y(n_163));
   NOR2BXL g21276__8246 (.AN(n_16),
	.B(n_20),
	.Y(n_182));
   INVXL g21289 (.A(n_354),
	.Y(n_247));
   NAND3XL g21298__7098 (.A(instruction[11]),
	.B(instruction[8]),
	.C(n_9),
	.Y(n_370));
   NOR2BXL g21291__6131 (.AN(n_21),
	.B(n_23),
	.Y(n_150));
   NOR2BXL g21272__1881 (.AN(n_12),
	.B(n_14),
	.Y(n_89));
   NOR2BXL g21293__5115 (.AN(n_16),
	.B(n_18),
	.Y(n_171));
   NOR2XL g21285__7482 (.A(n_13),
	.B(n_15),
	.Y(n_101));
   NOR2BXL g21275__4733 (.AN(n_10),
	.B(n_15),
	.Y(n_70));
   AND2X1 g21268__6161 (.A(n_21),
	.B(n_16),
	.Y(n_178));
   NOR2XL g21277__9315 (.A(n_11),
	.B(n_14),
	.Y(n_96));
   NOR2XL g21281__9945 (.A(n_13),
	.B(n_7),
	.Y(n_108));
   NOR2BXL g21282__2883 (.AN(n_12),
	.B(n_13),
	.Y(n_102));
   NOR2XL g21283__2346 (.A(n_13),
	.B(n_11),
	.Y(n_107));
   NOR2BXL g21284__1666 (.AN(n_12),
	.B(n_8),
	.Y(n_86));
   AND2X1 g21274__7410 (.A(n_10),
	.B(n_12),
	.Y(n_78));
   NAND2XL g21267__6417 (.A(instruction[12]),
	.B(n_480),
	.Y(n_24));
   INVXL g21320 (.A(n_600),
	.Y(n_374));
   INVXL g21287 (.A(n_352),
	.Y(n_243));
   INVXL g21288 (.A(n_355),
	.Y(n_246));
   NAND2XL g21290__5477 (.A(n_9),
	.B(n_480),
	.Y(n_28));
   INVXL g21321 (.A(n_599),
	.Y(n_533));
   NOR2XL g21280__2398 (.A(n_11),
	.B(n_8),
	.Y(n_81));
   NOR2BXL g21295__5107 (.AN(n_10),
	.B(n_11),
	.Y(n_93));
   NOR2XL g21303__6260 (.A(n_15),
	.B(n_8),
	.Y(n_91));
   NOR2BXL g21299__4319 (.AN(n_10),
	.B(n_7),
	.Y(n_94));
   NOR2XL g21300__8428 (.A(n_15),
	.B(n_14),
	.Y(n_88));
   NOR2XL g21301__5526 (.A(n_8),
	.B(n_7),
	.Y(n_82));
   NOR2XL g21294__6783 (.A(n_18),
	.B(n_23),
	.Y(n_158));
   NOR2XL g21305__3680 (.A(n_14),
	.B(n_7),
	.Y(n_97));
   NOR3XL g21306__1617 (.A(instruction[15]),
	.B(instruction[11]),
	.C(instruction[8]),
	.Y(n_352));
   NOR3BXL g21307__2802 (.AN(instruction[11]),
	.B(instruction[15]),
	.C(instruction[8]),
	.Y(n_355));
   NOR3BXL g21308__1705 (.AN(instruction[8]),
	.B(instruction[15]),
	.C(instruction[11]),
	.Y(n_354));
   INVXL g21309 (.A(n_551),
	.Y(n_541));
   NAND2XL g21328__8246 (.A(instruction[6]),
	.B(n_6),
	.Y(n_20));
   NAND2XL g21327__7098 (.A(instruction[4]),
	.B(n_5),
	.Y(n_22));
   NAND2XL g21326__6131 (.A(instruction[5]),
	.B(n_4),
	.Y(n_17));
   NAND2XL g21329__1881 (.A(instruction[7]),
	.B(n_3),
	.Y(n_19));
   NAND2XL g21311__7482 (.A(instruction[4]),
	.B(instruction[7]),
	.Y(n_23));
   NOR2XL g21313__4733 (.A(instruction[2]),
	.B(instruction[1]),
	.Y(n_10));
   NAND2BXL g21315__6161 (.AN(instruction[2]),
	.B(instruction[1]),
	.Y(n_14));
   NAND2XL g21325__9315 (.A(instruction[5]),
	.B(instruction[6]),
	.Y(n_18));
   NAND2XL g21310__9945 (.A(instruction[1]),
	.B(instruction[2]),
	.Y(n_13));
   NAND2XL g21312__2883 (.A(instruction[0]),
	.B(instruction[3]),
	.Y(n_11));
   NAND2XL g21319__2346 (.A(instruction[12]),
	.B(instruction[13]),
	.Y(n_551));
   NAND2BXL g21324__1666 (.AN(instruction[1]),
	.B(instruction[2]),
	.Y(n_8));
   NOR2XL g21317__7410 (.A(instruction[3]),
	.B(instruction[0]),
	.Y(n_12));
   NOR2XL g21314__6417 (.A(instruction[7]),
	.B(instruction[4]),
	.Y(n_16));
   NOR2XL g21323__5477 (.A(instruction[6]),
	.B(instruction[5]),
	.Y(n_21));
   NAND2BXL g21322__2398 (.AN(instruction[0]),
	.B(instruction[3]),
	.Y(n_7));
   NAND2BXL g21316__5107 (.AN(instruction[3]),
	.B(instruction[0]),
	.Y(n_15));
   NOR2XL g21318__6260 (.A(instruction[14]),
	.B(instruction[13]),
	.Y(n_480));
   INVXL g21338 (.A(instruction[14]),
	.Y(n_2));
   INVXL g21339 (.A(instruction[7]),
	.Y(n_5));
   INVXL g21337 (.A(instruction[15]),
	.Y(n_9));
   INVXL g21334 (.A(instruction[4]),
	.Y(n_3));
   INVXL g21333 (.A(instruction[5]),
	.Y(n_6));
   INVXL g21332 (.A(instruction[6]),
	.Y(n_4));
   INVXL g21340 (.A(instruction[9]),
	.Y(n_280));
   CLKINVX2 g21341 (.A(reset),
	.Y(n_584));
   NOR2BX1 g21484 (.AN(n_373),
	.B(n_372),
	.Y(n_596));
   NOR2BX1 g21485 (.AN(n_372),
	.B(n_373),
	.Y(n_597));
   NOR2BX1 g21486 (.AN(n_195),
	.B(instruction[10]),
	.Y(n_598));
   NOR2BX1 g21487 (.AN(instruction[13]),
	.B(instruction[12]),
	.Y(n_599));
   NOR2BX1 g21488 (.AN(instruction[12]),
	.B(instruction[13]),
	.Y(n_600));
   NAND3BX1 g21489 (.AN(n_533),
	.B(n_504),
	.C(n_602),
	.Y(n_601));
   NAND3BX1 g21490 (.AN(n_472),
	.B(n_473),
	.C(n_525),
	.Y(n_602));
   AO21X1 g21491 (.A0(n_528),
	.A1(n_441),
	.B0(n_456),
	.Y(n_603));
   NAND3X1 g21492 (.A(n_128),
	.B(n_166),
	.C(n_224),
	.Y(n_604));
   NAND3X1 g21493 (.A(n_127),
	.B(n_124),
	.C(n_232),
	.Y(n_605));
   NAND2XL g21494 (.A(n_606),
	.B(n_541),
	.Y(n_607));
   MXI2XL g3 (.A(n_532),
	.B(n_445),
	.S0(n_523),
	.Y(n_606));
   SDFFRHQX1 \reg_file_reg[9][0]  (.CK(clk),
	.D(\reg_file[9] [0]),
	.Q(\reg_file[9] [0]),
	.RN(n_584),
	.SE(n_570),
	.SI(n_514));
   SDFFRHQX1 \reg_file_reg[10][0]  (.CK(clk),
	.D(\reg_file[10] [0]),
	.Q(\reg_file[10] [0]),
	.RN(n_584),
	.SE(n_569),
	.SI(n_514));
   SDFFRHQX1 \reg_file_reg[11][0]  (.CK(clk),
	.D(\reg_file[11] [0]),
	.Q(\reg_file[11] [0]),
	.RN(n_584),
	.SE(n_568),
	.SI(n_514));
   SDFFRHQX1 \reg_file_reg[2][0]  (.CK(clk),
	.D(\reg_file[2] [0]),
	.Q(\reg_file[2] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_577),
	.SI(n_514));
   SDFFRHQX1 \reg_file_reg[3][0]  (.CK(clk),
	.D(\reg_file[3] [0]),
	.Q(\reg_file[3] [0]),
	.RN(FE_OFN588_n_584),
	.SE(n_576),
	.SI(n_514));
endmodule

